### ISSUE TITLE
Using panos_object module fails

### ISSUE THREAD

**Issue by zenemichels** [PaloAltoNetworks/ansible-pan#105]
I am trying to run a playbook to add an address object to a PA-VM we have for testing. I installed the PAN modules through ansible-galaxy. The playbook fails with the error below:

`The full traceback is:
  File "/var/folders/_q/p30qm43s72d92qxztqhtl_vc0000gn/T/ansible_IVoUOA/ansible_module_panos_object.py", line 167, in <module>
    from pan.xapi import PanXapiError

fatal: [fw01: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address": "1.1.1.1",
            "address_type": "ip-netmask",
            "addressgroup": null,
            "addressobject": "Cloudflare DNS",
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "color": null,
            "description": null,
            "destination_port": null,
            "devicegroup": null,
            "dynamic_value": null,
            "ip_address": "192.168.1.1",
            "operation": "add",
            "password": null,
            "protocol": null,
            "servicegroup": null,
            "serviceobject": null,
            "services": null,
            "source_port": null,
            "static_value": null,
            "tag_name": null,
            "username": "admin"
        }
    },
    "msg": "Missing required libraries."
}`

Not sure what libraries I'm missing because the module installs all required libraries when it runs.

**Comment by shinmog** [comment]
@zenemichels 

It seems like the python libraries weren't installed.  In the above, you're missing `pan-python`, which probably means you're also missing `pandevice`.  And if you're missing that, then you are also probably missing `xmltodict`.  I'd recommend making sure all of these are installed, and the error should go away.

**Comment by gliptak** [comment]
Is this the recommended install step?

```pip install ansible pan-python pandevice xmltodict```

PS I also had to run ```pip install pytest-runner```

https://github.com/PaloAltoNetworks/ansible-pan/blob/develop/setup.py#L40

**Comment by yi2020** [comment]
@gliptak I installed all four packages you mentioned via pip3, still getting the error:
`fw1 | FAILED! => {
    "changed": false,
    "msg": "Missing required libraries."
}`

How did you debug this?

**Comment by gliptak** [comment]
@yi2020  The one difference might have been running with ```python2```. Otherwise, just installed packages referenced above and it started working ...

**Comment by yi2020** [comment]
@ivanbojer can you assist perhaps?

**Comment by lcwittebol** [comment]
If this topic is still open?; I have the same issue

I have installed the required modules pan-python/pandevice/xmltodict

when i run a simple playbook from the examples
- name: Wait for FW reboot
      panos_check:
        provider: '{{ my_provider }}'
      register: result
      until: not result is failed
      retries: 1
      delay: 5

I get 
TASK [PaloAltoNetworks.paloaltonetworks : Install pandevice required library] *****************************************************************************
ok: [fw-dr-pa-1]

TASK [PaloAltoNetworks.paloaltonetworks : Install xmltodict required library] *****************************************************************************
ok: [fw-dr-pa-1]

TASK [set_fact] *******************************************************************************************************************************************
ok: [fw-dr-pa-1]

FAILED! => {"attempts": 1, "changed": false, "msg": "Missing required library \"pandevice\"."}

any pointers would be appreciated

**Comment by duganth** [comment]
On a mac, I was having the same problem, I attribute my issue with installing ansible with brew. When running the playbook it would look to 
`/usr/local/Cellar/ansible/2.8.3/libexec/bin/python3.7` to run the python modules. 

Your playbook passes the other library requirements because it specifically looks at (well in my case) 
`/usr/local/bin/pip3` for the libraries...
I just set the python manually for now and it works fine,
```
vars:
  ansible_python_interpreter: /usr/local/bin/python3
```

 I havn't looked at how to set brew right or maybe uninstalling with brew and installing manually.  


HTH

**Comment by luckylittle** [comment]
I'm hitting this as well on Red Hat Ansible Tower `v3.5.3` with custom environment with the following Python2 modules:

```
Package      Version
------------ -------
ansible      2.8.5
asn1crypto   1.2.0
cffi         1.13.0
cryptography 2.7
enum34       1.1.6
ipaddress    1.0.22
Jinja2       2.10.3
MarkupSafe   1.1.1
pan-python   0.15.0
pandevice    0.12.0
pip          19.3
psutil       5.6.3
pycparser    2.19
PyYAML       5.1.2
setuptools   28.8.0
six          1.12.0
wheel        0.29.0
```

Error is simply `"msg": "Missing required libraries."`

**Comment by JulioPDX** [comment]
Late to the party but if someone sees this, just set whatever group your firewall is in to the correct venv if using one. Battled with this for too long...
example
```
[pa_200]
my-firewall ansible_host=192.168.1.1

[firewalls:children]
pa_200

[firewalls:vars]
ansible_python_interpreter=/home/juliopdx/myvenv/bin/python
```
