### ISSUE TITLE
cmd_is_xml does not register as a valid option

### ISSUE THREAD

**Issue by jcoeder** [PaloAltoNetworks/ansible-pan#107]
When attempting to use the option cmd_is_xml within panos_op the following error is thrown:

fatal: [edge-firewall-1-a]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (panos_op) module: cmd_is_xml Supported parameters include: api_key, cmd, ip_address, password, username"}

- name: Fetching Latest Licensing
  hosts: firewall-cluster
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Fetch Latest Licensing
    panos_op:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'
      cmd_xml: True
      cmd: '<operations><request><license><fetch/></license></request></operations></request>'
    register: result

  - name: returned output in the default JSON format
    debug: msg='{{ result.stdout }}'

  - name: returned output in the XML format
    debug: msg='{{ result.stdout_xml }}'

**Comment by shinmog** [comment]
Verified this is a valid option in newer ansible galaxy roles.  Make sure you're using PaloAltoNetworks.paloaltonetworks Ansible Galaxy role version 2.0.x.
