### ISSUE TITLE
panos_software api user does not have superuser permissions

### ISSUE THREAD

**Issue by jcoeder** [PaloAltoNetworks/ansible-pan#108]
I received the following error when running the included playbook using the API key and commenting out the username and password options.

TASK [Install PAN-OS and restart] ************************************************************************************************************
fatal: [edge-firewall-1-a]: FAILED! => {"changed": false, "msg": "You need superuser privileges to do that"}
	to retry, use: --limit @/home/justin/ansible/palo-alto-update/update-a.retry

PLAY RECAP ***********************************************************************************************************************************
edge-firewall-1-a          : ok=4    changed=0    unreachable=0    failed=1   

- name: Updating Firewall
  hosts: firewall-a
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Install PAN-OS and restart
    panos_software:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      #API user doesn't have superuser permissions even when configured
      #api_key: '{{ api_key }}'
      version: '8.0.6'
      restart: true

admin@FW2(active)# show shared admin-role API_USER 
(container-tag: shared container-tag: admin-role container-tag: entry key-tag: name value: API_USER)
((eol-matched: . #t) (eol-matched: . #t) (xpath-prefix: . /config) (context-inserted-at-end-p: . #f))
/usr/local/bin/pan_ms_client --config-mode=default --set-prefix='set shared admin-role ' --cookie=3905953953271814 <<'EOF'  |sed 2>/dev/null -e 's/devices localhost.localdomain//'  |/usr/bin/less -X -E -M
<request cmd="get" obj="/config/shared/admin-role/entry[@name='API_USER']"></request>
EOF

API_USER {
  role {
    device {
      webui {
        dashboard enable;
        acc enable;
        monitor {
          logs {
            traffic enable;
            threat enable;
            url enable;
            wildfire enable;
            data-filtering enable;
            hipmatch enable;
            userid enable;
            tunnel enable;
            configuration enable;
            system enable;
            alarm enable;
            authentication enable;
          }
          automated-correlation-engine {
            correlation-objects enable;
            correlated-events enable;
          }
          packet-capture enable;
          app-scope enable;
          session-browser enable;
          botnet enable;
          pdf-reports {
            manage-pdf-summary enable;
            pdf-summary-reports enable;
            user-activity-report enable;
            saas-application-usage-report enable;
            report-groups enable;
            email-scheduler enable;
          }
          custom-reports {
            application-statistics enable;
            data-filtering-log enable;
            threat-log enable;
            threat-summary enable;
            traffic-log enable;
            traffic-summary enable;
            url-log enable;
            url-summary enable;
            hipmatch enable;
            wildfire-log enable;
            tunnel-log enable;
            tunnel-summary enable;
            userid enable;
            auth enable;
          }
          view-custom-reports enable;
          application-reports enable;
          threat-reports enable;
          url-filtering-reports enable;
          traffic-reports enable;
        }
        policies {
          security-rulebase enable;
          nat-rulebase enable;
          qos-rulebase enable;
          pbf-rulebase enable;
          ssl-decryption-rulebase enable;
          tunnel-inspect-rulebase enable;
          application-override-rulebase enable;
          authentication-rulebase enable;
          dos-rulebase enable;
        }
        objects {
          addresses enable;
          address-groups enable;
          regions enable;
          applications enable;
          application-groups enable;
          application-filters enable;
          services enable;
          service-groups enable;
          tags enable;
          global-protect {
            hip-objects enable;
            hip-profiles enable;
          }
          dynamic-block-lists enable;
          custom-objects {
            data-patterns enable;
            spyware enable;
            vulnerability enable;
            url-category enable;
          }
          security-profiles {
            antivirus enable;
            anti-spyware enable;
            vulnerability-protection enable;
            url-filtering enable;
            file-blocking enable;
            wildfire-analysis enable;
            data-filtering enable;
            dos-protection enable;
          }
          security-profile-groups enable;
          log-forwarding enable;
          authentication enable;
          decryption-profile enable;
          schedules enable;
        }
        network {
          interfaces enable;
          zones enable;
          vlans enable;
          virtual-wires enable;
          virtual-routers enable;
          ipsec-tunnels enable;
          dhcp enable;
          dns-proxy enable;
          global-protect {
            portals enable;
            gateways enable;
            mdm enable;
            device-block-list enable;
            clientless-apps enable;
            clientless-app-groups enable;
          }
          qos enable;
          lldp enable;
          network-profiles {
            gp-app-ipsec-crypto enable;
            ike-gateways enable;
            ipsec-crypto enable;
            ike-crypto enable;
            tunnel-monitor enable;
            interface-mgmt enable;
            zone-protection enable;
            qos-profile enable;
            lldp-profile enable;
            bfd-profile enable;
          }
        }
        device {
          setup {
            management enable;
            operations enable;
            services enable;
            content-id enable;
            wildfire enable;
            session enable;
            hsm enable;
          }
          high-availability enable;
          config-audit enable;
          administrators read-only;
          admin-roles read-only;
          authentication-profile enable;
          authentication-sequence enable;
          user-identification enable;
          vm-info-source enable;
          certificate-management {
            certificates enable;
            certificate-profile enable;
            ocsp-responder enable;
            ssl-tls-service-profile enable;
            scep enable;
            ssl-decryption-exclusion enable;
          }
          block-pages enable;
          log-settings {
            system enable;
            config enable;
            user-id enable;
            hipmatch enable;
            cc-alarm enable;
            manage-log enable;
          }
          server-profile {
            snmp-trap enable;
            syslog enable;
            email enable;
            http enable;
            netflow enable;
            radius enable;
            tacplus enable;
            ldap enable;
            kerberos enable;
            saml_idp enable;
            mfa enable;
          }
          local-user-database {
            users enable;
            user-groups enable;
          }
          scheduled-log-export enable;
          software enable;
          global-protect-client enable;
          dynamic-updates enable;
          licenses enable;
          support enable;
          master-key enable;
        }
        privacy {
          show-full-ip-addresses enable;
          show-user-names-in-logs-and-reports enable;
          view-pcap-files enable;
        }
        validate enable;
        save {
          partial-save enable;
          save-for-other-admins enable;
        }
        commit {
          device enable;
          commit-for-other-admins enable;
        }
        tasks enable;
        global {
          system-alarms enable;
        }
      }
      xmlapi {
        report enable;
        log enable;
        config enable;
        op enable;
        commit enable;
        user-id enable;
        export enable;
        import enable;
      }
      cli superuser;
    }
  }
  description API_USER;
}

**Comment by shinmog** [comment]
@jcoeder 

Try with the `admin` user, maybe?  If it works with admin but not your custom admin, then you must be missing a permission somewhere.

**Comment by shinmog** [comment]
This seems to be resolved, aging this issue out.
