### ISSUE TITLE
Unsupported parameters for (panos_security_rule) module: log_setting (V1.0.8)

### ISSUE THREAD

**Issue by remi1411** [PaloAltoNetworks/ansible-pan#109]
Hello,

I'm working on the version (V1.0.8), i see new module log_setting for panos_security_rule have been added but i have the following error : 
`fatal: [my-panorama]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (panos_security_rule) module: log_setting Supported parameters include: action, antivirus, api_key, application, category, commit, data_filtering, description, destination_ip, destination_zone, devicegroup, existing_rule, file_blocking, group_profile, hip_profiles, ip_address, is_post_rule, location, log_end, log_start, operation, password, rule_name, rule_type, service, source_ip, source_user, source_zone, spyware, tag_name, url_filtering, username, vulnerability, wildfire_analysis"}`

Thanks for your amazing work !

**Comment by shinmog** [comment]
@remi1411 
The `log_setting` enhancement for `panos_security_rule` hasn't been pushed to Ansible Galaxy yet.  This is coming soon.

**Comment by ivanbojer** [comment]
Please reopen if issue still exists. It should have been fixed with 2.0.1 and on Galaxy.
