### ISSUE TITLE
"Unsupported parameters for (panos_object) module: " err with 'show system info'

### ISSUE THREAD

**Issue by rabdhir** [PaloAltoNetworks/ansible-pan#114]
root@usvr-1804:/home/labadmin# ansible-playbook panos_operation.yml -vvv
ansible-playbook 2.5.1
  config file = /home/labadmin/ansible.cfg
  configured module search path = [u'/etc/ansible/roles/PaloAltoNetworks.paloaltonetworks']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Using /home/labadmin/ansible.cfg as config file
Parsed /home/labadmin/hosts inventory source with ini plugin

PLAYBOOK: panos_operation.yml ***********************************************************************************************************************************************************
1 plays in panos_operation.yml

PLAY [Start ansible in automation lab] **************************************************************************************************************************************************
META: ran handlers

TASK [PaloAltoNetworks.paloaltonetworks : pip] ******************************************************************************************************************************************
task path: /etc/ansible/roles/PaloAltoNetworks.paloaltonetworks/tasks/main.yml:5
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/language/pip.py
<pa-5250-1> ESTABLISH LOCAL CONNECTION FOR USER: root
<pa-5250-1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576 `" && echo ansible-tmp-1535669935.28-279980040274576="` echo /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576 `" ) && sleep 0'
<pa-5250-1> PUT /root/.ansible/tmp/ansible-local-213055sPzPm/tmpDCGlFM TO /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576/pip.py
<pa-5250-1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576/ /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576/pip.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576/pip.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1535669935.28-279980040274576/ > /dev/null 2>&1 && sleep 0'
ok: [pa-5250-1] => {
    "changed": false,
    "cmd": "/usr/bin/pip2 install pan-python",
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "pan-python"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "use_mirrors": true,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "name": [
        "pan-python"
    ],
    "requirements": null,
    "state": "present",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Requirement already satisfied: pan-python in /root/.local/lib/python2.7/site-packages\n",
    "stdout_lines": [
        "Requirement already satisfied: pan-python in /root/.local/lib/python2.7/site-packages"
    ],
    "version": null,
    "virtualenv": null
}

TASK [PaloAltoNetworks.paloaltonetworks : pip] ******************************************************************************************************************************************
task path: /etc/ansible/roles/PaloAltoNetworks.paloaltonetworks/tasks/main.yml:7
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/language/pip.py
<pa-5250-1> ESTABLISH LOCAL CONNECTION FOR USER: root
<pa-5250-1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543 `" && echo ansible-tmp-1535669936.5-231467202918543="` echo /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543 `" ) && sleep 0'
<pa-5250-1> PUT /root/.ansible/tmp/ansible-local-213055sPzPm/tmpEuESWj TO /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543/pip.py
<pa-5250-1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543/ /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543/pip.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543/pip.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1535669936.5-231467202918543/ > /dev/null 2>&1 && sleep 0'
ok: [pa-5250-1] => {
    "changed": false,
    "cmd": "/usr/bin/pip2 install pandevice",
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "pandevice"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "use_mirrors": true,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "name": [
        "pandevice"
    ],
    "requirements": null,
    "state": "present",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Requirement already satisfied: pandevice in /usr/local/lib/python2.7/dist-packages\nRequirement already satisfied: pan-python in /root/.local/lib/python2.7/site-packages (from pandevice)\n",
    "stdout_lines": [
        "Requirement already satisfied: pandevice in /usr/local/lib/python2.7/dist-packages",
        "Requirement already satisfied: pan-python in /root/.local/lib/python2.7/site-packages (from pandevice)"
    ],
    "version": null,
    "virtualenv": null
}

TASK [PaloAltoNetworks.paloaltonetworks : pip] ******************************************************************************************************************************************
task path: /etc/ansible/roles/PaloAltoNetworks.paloaltonetworks/tasks/main.yml:9
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/language/pip.py
<pa-5250-1> ESTABLISH LOCAL CONNECTION FOR USER: root
<pa-5250-1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619 `" && echo ansible-tmp-1535669938.14-203358969134619="` echo /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619 `" ) && sleep 0'
<pa-5250-1> PUT /root/.ansible/tmp/ansible-local-213055sPzPm/tmpFnvoC5 TO /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619/pip.py
<pa-5250-1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619/ /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619/pip.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619/pip.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1535669938.14-203358969134619/ > /dev/null 2>&1 && sleep 0'
ok: [pa-5250-1] => {
    "changed": false,
    "cmd": "/usr/bin/pip2 install xmltodict",
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "xmltodict"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "use_mirrors": true,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "name": [
        "xmltodict"
    ],
    "requirements": null,
    "state": "present",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Requirement already satisfied: xmltodict in /usr/lib/python2.7/dist-packages\n",
    "stdout_lines": [
        "Requirement already satisfied: xmltodict in /usr/lib/python2.7/dist-packages"
    ],
    "version": null,
    "virtualenv": null
}

TASK [show list of all interfaces] ******************************************************************************************************************************************************
task path: /home/labadmin/panos_operation.yml:12
Using module file /etc/ansible/roles/PaloAltoNetworks.paloaltonetworks/library/panos_object.py
<pa-5250-1> ESTABLISH LOCAL CONNECTION FOR USER: root
<pa-5250-1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642 `" && echo ansible-tmp-1535669939.5-16124905585642="` echo /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642 `" ) && sleep 0'
<pa-5250-1> PUT /root/.ansible/tmp/ansible-local-213055sPzPm/tmp6tpxAu TO /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642/panos_object.py
<pa-5250-1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642/ /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642/panos_object.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642/panos_object.py && sleep 0'
<pa-5250-1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1535669939.5-16124905585642/ > /dev/null 2>&1 && sleep 0'
fatal: [pa-5250-1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cmd": "show interfaces all",
            "ip_address": "10.2.127.73",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Unsupported parameters for (panos_object) module: cmd Supported parameters include: address, address_type, addressgroup, addressobject, api_key, color, description, destination_port, devicegroup, dynamic_value, ip_address, operation, password, protocol, servicegroup, serviceobject, services, source_port, static_value, tag_name, username"
}
        to retry, use: --limit @/home/labadmin/panos_operation.retry

PLAY RECAP ******************************************************************************************************************************************************************************
pa-5250-1                  : ok=3    changed=0    unreachable=0    failed=1

root@usvr-1804:/home/labadmin# cat panos_operation.yml
---
- name: Start ansible in automation lab
  hosts: pa-5250-1
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

    - name: show list of all interfaces
      panos_object:
        ip_address: "10.2.127.73"
        username: "admin"
        password: "admin"
        cmd: 'show interfaces all'

      register: print_output

    - debug: var=print_output

    - name: set admin password
      panos_object:
        ip_address: "10.2.127.73"
        username: "admin"
        password: "admin"
        cmd: 'show system info'

      register: print_output

    - debug: var=print_output

root@usvr-1804:/home/labadmin#

**Comment by shinmog** [comment]
@rabdhir 
You're using `panos_object` instead of `panos_op` in your playbook.
