### ISSUE TITLE
Documentation link is incorrect

### ISSUE THREAD

**Issue by stealthllama** [PaloAltoNetworks/ansible-pan#120]
The current README.md contains this broken link: [https://pages.github.io/PaloAltoNetwokrs/ansible-pan](https://pages.github.io/PaloAltoNetwokrs/ansible-pan)

Seems like it should point to [https://paloaltonetworks.github.io/ansible-pan/](https://paloaltonetworks.github.io/ansible-pan) instead.

**Comment by shinmog** [comment]
fixed, ty
