### ISSUE TITLE
panos_security_rule module - rule_is_match() fails to match due to empty description

### ISSUE THREAD

**Issue by jacobsnapp** [PaloAltoNetworks/ansible-pan#124]
**Context:**
I exported some existing rules from a PA-VM. I have tried to "add" the rule to the firewall to test if the module is idempotent. The expected behaviour is that the rule_is_match() function should identify the rule is an exact match and continue. However, if a rule does not have the description, the JSON exported from the firewall does not have a "description" element (ie. description: null). Currently the default for an omitted description parameter is not null, but an empty string "". This causes the rule_is_match to fail because it is comparing "" with null.

panos_security_rule:
        description: "{{ item.description | default(omit) }}"

**Issue:**
Currently the argument_spec of the panos_security_rule module has the description default value as ''.

argument_spec = dict(...
        description=dict(default=''),
        .....

**Solution:**

argument_spec = dict(...
        description=dict(),
        .....

TEST PLAYBOOK

- name: Playbook
  hosts: panos
  connection: local
  vars:
    ansible_python_interpreter:  "/home/vagrant/py2-dev/bin/python2"
  gather_facts: False
  tasks:
    - name: Load in JSON Rulebase
      include_vars:
        file: rule.json
        name: rulebase
    - name: Adding Security Rules
      panos_security_rule:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        operation: "{{ item.operation | default('add') }}"
        rule_name: "{{ item['@name'] }}"
        rule_type: "{{ item.rule_type | default(omit) }}" 
        description: "{{ item.description | default(omit) }}"
        tag_name: "{{ item.tag_name | default(omit) }}"
        source_zone: "{{ item.from.member | default(omit) }}"
        destination_zone: "{{ item.to.member | default(omit) }}"
        source_ip: "{{ item.source.member | default(omit) }}"
        source_user: "{{ item['source-user'].member | default(omit) }}"
        hip_profiles: "{{ item['hip-profiles'].member | default(omit) }}"
        destination_ip: "{{ item.destination.member | default(omit) }}"
        category: "{{ item.category.member | default(omit) }}"
        application: "{{ item.application.member | default(omit) }}"
        service: "{{ item.service.member | default(omit) }}"
        action: "{{ item.action | default(omit) }}"
        log_start: "{{ item.log_start | default(omit) }}"
        log_end: "{{ item.log_end | default(omit) }}"
        log_setting: "{{ item.log_setting | default(omit) }}"
        group_profile: "{{ item.group_profile | default(omit)}}"
        antivirus: "{{ item.antivirus | default(omit) }}"
        vulnerability: "{{ item.vulnerability | default(omit) }}"
        spyware: "{{ item.spyware | default(omit) }}"
        url_filtering: "{{ item.url_filtering | default(omit) }}"
        file_blocking: "{{ item.file_blocking | default(omit) }}"
        data_filtering: "{{ item.data_filtering | default(omit) }}"
        wildfire_analysis: "{{ item.wildfire_analysis | default(omit) }}"
        devicegroup: "{{ item.devicegroup | default(omit) }}"
        location: "{{ item.location | default(omit) }}"
        existing_rule: "{{ item.existing_rule | default(omit) }}"
        commit: "{{ item.commit | default(omit) }}"
      register: output
      with_items:
        - "{{ rulebase }}"

**Comment by shinmog** [comment]
`panos_security_rule` has been made idempotent and now sports `state` of "present" or "absent".  The old `operation` param is deprecated and will be soft removed in v2.1.0 of the Palo Alto Networks Ansible role.
