### ISSUE TITLE
panos_commit - Panorama commits to device group but not to Panorama

### ISSUE THREAD

**Issue by ngobert** [PaloAltoNetworks/ansible-pan#132]
When using the panos_commit module with Panorama (v8.1 tested), the "Commit All" operation attempts to commit to the specified device group.  When used in a playbook to modify a configuration, this will does push the modified configuration, as version 8.x requires first committing the changes to Panorama, then to the device group.  

Commits to a device group should be updated to perform two commit operations:
1 - Commit to the Panorama device (device.commit)
2 - Commit to the device group (device.commit_all)

**Comment by ivanbojer** [comment]
This should've been fixed with pull #143 . Please reopen if not.
