### ISSUE TITLE
panos_security_rule: Security Policy position/order

### ISSUE THREAD

**Issue by davidcoulson** [PaloAltoNetworks/ansible-pan#14]
I have successfully created a security policy on my PAN instance, however the rule is populated at the bottom of the security policies which in some instances is undesirable. A alternate approach would be to identify either specific rule number, or name of rule above/below new rule.

I'm digging into the pandevice code a bit, so I'm not 100% sure if it is a constraint of pandevice, or there is the opportunity to add additional parameters to panos_security_policy.

**Comment by ivanbojer** [comment]
In development branch. 
https://github.com/PaloAltoNetworks/ansible-pan/pull/81
