### ISSUE TITLE
Question about modules using devicegroup

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/ansible-pan#141]
This is more of curiosity.

It seems that all the modules that have panorama support (say for example panos_security_rule) are designed to use "devicegroup" as a way to specify the firewall where the policy should be installed. We have our devicegroup specified by country (more then one cluster in each group), so if we are trying to push the polices through panorama i guess we have to create one devicegroup per cluster.

Was there any reason devicegroup was picked and not other ways of specify the the firewall to target through panorama?

**Comment by ishuguru** [comment]
Thanks for the clarifications 👍  
In that case im looking forward to the features you mention being implemented (aswell as the l2/l3 interface that i see being discussed in a other thread)

Thanks for a good job :-)

**Comment by shinmog** [comment]
np :)
