### ISSUE TITLE
panos_lic module

### ISSUE THREAD

**Issue by torstenstern** [PaloAltoNetworks/ansible-pan#148]
Hi there,

i try to use the panos_lic module but i get everytime an syntax error when i use it.

The offending line appears to be:

    - name: fetch license
    ^ here

* null_resource.configure_firewalls[1]: Error running command '': exit status 4. Output:  [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'
ERROR! Syntax Error while loading YAML.
  did not find expected key

**Comment by shinmog** [comment]
Closing as this seems like a playbook formatting issue and no response for over 5 months.
