### ISSUE TITLE
panos_ipsec_tunnel generates error on comparing against existing ipsec tunnel

### ISSUE THREAD

**Issue by peter-murray** [PaloAltoNetworks/ansible-pan#150]
When there is an existing ipsec tunnel the code at https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_ipsec_tunnel.py#L195 generates an error of `AttributeError: equals`.

Looking at the code for pandevice I think this should be `equal` as per doumentation https://pandevice.readthedocs.io/en/latest/module-base.html#pandevice.base.VersionedPanObject.equal

**Comment by shinmog** [comment]
@peter-murray 

Fixed, ty for the catch!
