### ISSUE TITLE
panos_object not idempotent

### ISSUE THREAD

**Issue by victorock** [PaloAltoNetworks/ansible-pan#172]
I appreciate all the efforts to put together these modules, and all the on-going development.

With the current implementation, when using operation "add" and running the same playbook twice, users will get error saying that the entry already exists and operations should be "update".

In order to have idempotent modules, the approach should be based on states: present/absent, and the module implementation ensure the desired state.

**Comment by stealthllama** [comment]
The `operation` parameter had to be kept in the 2.0.0 release for backwards compatibility and will eventually be phased out. You can now use the `state` parameter as you've described for idempotent functionality. The two parameters are mutually exclusive.

**Comment by shinmog** [comment]
@victorock @stealthllama 
The `state` param wasn't added to `panos_object`.  `panos_object` is now deprecated in favor of the specific modules:  `panos_address_object`, `panos_address_group`, etc.
