### ISSUE TITLE
Unsupported parameters for (panos_security_rule) module: existing_rule

### ISSUE THREAD

**Issue by nehafish** [PaloAltoNetworks/ansible-pan#177]
I'm using Ansible ver 2.7.0 with the latest ansible-pan:master branch. It seems the 'existing_rule parameter' is not supported?

I'm defining the location after the action parameter, and existing_rule like so:

```
      action: 'allow'
      location: 'before'
      existing_rule: 'PROD-SSH-TO-ANY'
      commit: 'False'
```

This yields:

     "msg": "Unsupported parameters for (panos_security_rule) module: existing_rule, location
     Supported parameters include: action, antivirus, api_key, application, category, commit,
     data_filtering, description, destination_ip, destination_zone, devicegroup, file_blocking, 
    group_profile, hip_profiles, ip_address, log_end, log_start, operation, password, rule_name, 
    rule_type, service, source_ip, source_user, source_zone, spyware, tag_name, url_filtering, 
    username, vulnerability, wildfire_analysis"

**Comment by freakinhippie** [comment]
I'm not sure if you figured this out yet, but the default branch for this is `develop`, not `master`. The master branch seems to follow the released version, and the *existing_rule* parameter has not made it into a release yet. If you switch to the `develop` branch you should have the functionality.

**Comment by nehafish** [comment]
Ah, thanks so much - I had not figured that out and I'm just getting back into work after vacation.
