### ISSUE TITLE
Is panos_check enough if upgrading a cluster?

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/ansible-pan#181]
Im planing on having a playbook for schedueling upgrading of a cluster. If i first do a upgrade on one node in the cluster, is panos_check the same as checking the device status in panoama (if its green)?

This is for knowing when to start upgrade of the second node.

**Comment by shinmog** [comment]
Right now, `panos_check` checks "show jobs all" and makes sure that everything is resolved, and is fine with initial connectivity issues (say, if PAN-OS is just coming up from a reboot).  I'm not sure what the green status is checking, but if you find out, performing that could be added as an alternative run-mode for `panos_check`.
