### ISSUE TITLE
TypeError: commit() got an unexpected keyword argument 'exceptions' in panos_interface module

### ISSUE THREAD

**Issue by freakinhippie** [PaloAltoNetworks/ansible-pan#185]
The panos_interface module raises an exception because the call to commit() includes *exceptions=True* but the it should be *exception=True*.

    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: commit() got an unexpected keyword argument 'exceptions'

**Comment by shinmog** [comment]
Fixed by #186
