### ISSUE TITLE
Support for layer3 subinterface

### ISSUE THREAD

**Issue by chewdevs** [PaloAltoNetworks/ansible-pan#194]
The `panos_interface` module cannot create subinterface and it may be needed when using VLAN.

**Comment by gnorkomat** [comment]
We encountered the same issue. Is there any known workaround?

**Comment by tdmakepeace** [comment]
additional request for sub-interface support.

**Comment by scubar** [comment]
Also an issue for me!

**Comment by fhlmbrg** [comment]
Hi @shinmog and @ivanbojer , is this feature on any roadmap? I noticed @matfreeman created a PR earlier, but it was closed due to your refactoring plans https://github.com/PaloAltoNetworks/ansible-pan/pull/100 .

**Comment by shinmog** [comment]
Subinterfaces will be coming in the next feature release of the role.

**Comment by fhlmbrg** [comment]
@shinmog thank you for the update :-) Excellent! Do you have any estimate on release date? Would be happy to test some early release code if available.

**Comment by shinmog** [comment]
Sometime after Ignite, heh :)

**Comment by shinmog** [comment]
Subinterfaces need two modules, one for l3, one for l2, so I'm changing this issue to be specific to L3 subinterfaces.
