### ISSUE TITLE
panos_static_route Fatal error by seletcting Interface

### ISSUE THREAD

**Issue by torstenstern** [PaloAltoNetworks/ansible-pan#202]
Hi,

i try to configure a static route with the selecting an Interface. When i check the module is it available but i am getting an error. See below my code an the error:

  - name: 'Route for Spoke 1'
    panos_static_route:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'Spoke 1'
      destination: '10.0.2.0/25'
      virtual_router: 'internal'
      interface: ethernet1/2
      nexthop: 10.0.1.129/32
      state: 'present'

but when i run it i am getting the following error:

TASK [Route for Spoke 1] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (panos_static_route) module: interface Supported parameters include: admin_dist, api_key, destination, ip_address, metric, name, nexthop, nexthop_type, password, state, username, virtual_router"}

**Comment by AdilKhan1117** [comment]
Hi
What was the fix?

Thank
