### ISSUE TITLE
Bump Ansible Core Version

### ISSUE THREAD

**Issue by Fobhep** [PaloAltoNetworks/ansible-pan#205]
Are there any plans on updating the Version of the Modules that are shipped with Ansible core? 
Those are quite a bit behind the version of this repo.

Related issue:
https://github.com/PaloAltoNetworks/ansible-pan/issues/99

**Comment by btorresgil** [comment]
@Fobhep Most vendors including Palo Alto Networks are moving away from modules in core Ansible code. It takes too long to get features and bug fixes out to you that way, and as Ansible invests more in Roles and the Ansible Galaxy ecosystem, that’s the direction we’re all headed. The modules in core will likely be deprecated at some point.

@ishuguru It may feel dead but the project is alive and well. We are currently slow to merge pull requests but are ramping up for some big moves.  Stay tuned!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fobhep** [comment]
@btorresgil yeah I have that feeling too.
Anyways thanks for clarifying that. I won't focus on the core-part then and instead stay with this repo :)
