### ISSUE TITLE
Why ansible-galaxy doesnt pull latest version??

### ISSUE THREAD

**Issue by pixelicous** [PaloAltoNetworks/ansible-pan#211]
I see the modules here are more updated than the ansible-galaxy version.
I guess it is because there is no release yet.
However resources such as panos_ike_Gateway have got more properties on them.. is there a beta version i can pull from ansible-galaxy that includes all latest changes?

**Comment by pixelicous** [comment]
Well i figured i can use ansible-galaxy install git+URL TO THIS REPO

**Comment by shinmog** [comment]
@pixelicous 

That's one way to do it I guess, heh.  We are updating the Ansible Galaxy role when we're confident in the quality.  The role was updated a few times since this issue was opened, and will be updated again relatively soon, so closing this issue.
