### ISSUE TITLE
Feature Request: network_cli

### ISSUE THREAD

**Issue by ryanmerolle** [PaloAltoNetworks/ansible-pan#220]
Per the recent push towards a standardized ansible network automation it would be good that this module was updated to follow this new approach.

https://www.ansible.com/blog/red-hat-ansible-network-automation-updates
https://docs.ansible.com/ansible/latest/plugins/connection/network_cli.html
https://docs.ansible.com/ansible/latest/network/user_guide/network_best_practices_2.5.html

**Comment by shinmog** [comment]
@ryanmerolle 

So I did investigate using the httpapi connection, but this ended up not making sense for the panos modules:

* the modules don't perform operations (by and large) over the CLI, but using the PAN-OS API
* PAN-OS has a specialized CLI as opposed to a standard linux CLI
* functions that httpapi seems to assume, such as copying a file over to the remote file system, just are not present / implemented in the PAN-OS CLI

After speaking with RedHat on this, they suggested that we could still create our own "connection" to help abstract out some stuff, which is the path that we are pursuing in the v2.1.0 release.
