### ISSUE TITLE
panos_op.py local variable xml_output referenced before assignment.

### ISSUE THREAD

**Issue by demakkar** [PaloAltoNetworks/ansible-pan#226]
**Trying to download the image from Palo Alto Update Servers using below code and it throws below error.**
`      - name: Download the software if Not downloaded Already
        panos_op:
          cmd: 'request system software download version "{{software_version}}"'
          username: "{{ cli_username }}"
          password: "{{ cli_password }}"
          ip_address: "{{ansible_host}}"
        environment:
          PYTHONHTTPSVERIFY: "{{ https_verify }}"
        register: software
        changed_when: false
        check_mode: no `

`The full traceback is:
Traceback (most recent call last):
  File "/home/demakkar/.ansible/tmp/ansible-tmp-1549907286.56-248854008324715/AnsiballZ_panos_op.py", line 113, in <module>
    _ansiballz_main()
  File "/home/demakkar/.ansible/tmp/ansible-tmp-1549907286.56-248854008324715/AnsiballZ_panos_op.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/demakkar/.ansible/tmp/ansible-tmp-1549907286.56-248854008324715/AnsiballZ_panos_op.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_panos_op_payload_1TJRUo/__main__.py", line 159, in <module>

  File "/tmp/ansible_panos_op_payload_1TJRUo/__main__.py", line 152, in main

**UnboundLocalError: local variable 'xml_output' referenced before assignment**

fatal: [tusredrwep52v2]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/demakkar/.ansible/tmp/ansible-tmp-1549907286.56-248854008324715/AnsiballZ_panos_op.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/demakkar/.ansible/tmp/ansible-tmp-1549907286.56-248854008324715/AnsiballZ_panos_op.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/demakkar/.ansible/tmp/ansible-tmp-1549907286.56-248854008324715/AnsiballZ_panos_op.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_op_payload_1TJRUo/__main__.py\", line 159, in <module>\n    \n  File \"/tmp/ansible_panos_op_payload_1TJRUo/__main__.py\", line 152, in main\n    \nUnboundLocalError: local variable 'xml_output' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
`

**Comment by shinmog** [comment]
This error is exists with the default panos Ansible modules in RedHat's `ansible/ansible` repo, but is fixed with the Palo Alto Networks galaxy role (which is built from this repo).  Please use the [PaloAltoNetworks.paloaltonetworks](https://galaxy.ansible.com/PaloAltoNetworks/paloaltonetworks) Galaxy role as it is much newer code than what is on `ansible/ansible`.
