### ISSUE TITLE
Issue with panos_content

### ISSUE THREAD

**Issue by SudarshanVK** [PaloAltoNetworks/ansible-pan#227]
panos_content modules fails with the below error message
 
"ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/mnt/c/Users/sudarshan kumar/Documents/XXXXXXXXXXXX/upgrade-firewall.yml': line 15, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Upgrade anti-virus and wildfire
      ^ here

The play that I am running loos like 

- name: Upgrade firewall
  hosts: paloalto
  connection: local
  gather_facts: False
  vars:
    ip_address: "x.x.x.x"
    username: "xxxxxx"
    password: "yyyyyyyy"

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

    - name: Upgrade anti-virus and wildfire
      panos_content:
        ip_address: "{{ ip_address }}"
        usernaame: "{{ username }}"
        password: "{{ password }}"
        anti_virus_update: yes
        wildfire_update: yes

**Comment by geraint-jones-nz** [comment]
`panos_content` isn't part of `ansible-pan` it's available here https://github.com/PaloAltoNetworks/appframeworklab/blob/master/ansible/library/panos_content.py 

But it should probably actually be added to the modules here.

**Comment by SudarshanVK** [comment]
Sorry if I am asking a stupid question, How do I add this module to my library?

**Comment by geraint-jones-nz** [comment]
https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html

That shoukd get you started :)

**Comment by SudarshanVK** [comment]
So I have already installed the role, in-fact I have met all requirements in "requirements.txt".
A little more help is appreciated. Sorry I am quite new to Ansible and don't understand every aspect of it.

**Comment by SudarshanVK** [comment]
ok. sorted that out.. thanks a ton..

**Comment by geraint-jones-nz** [comment]
@shinmog can we take `panos_content` from the `appframeworklab` and add it here? the examples refer to it; https://github.com/PaloAltoNetworks/ansible-pan/blob/develop/examples/fw_content.yml
