### ISSUE TITLE
Make all tasks idempotent

### ISSUE THREAD

**Issue by troxil** [PaloAltoNetworks/ansible-pan#23]
Hello, 

I believe that all of the tasks are not idempotent, which relies each task to be supplied with an 'operation' task. 

If you need to delete, the defacto approach is 'absent: True/False' vs 'operation: delete'. 
If you need to update, remove 'absent' and let it adjust as expected. 

If you're being super cautious with what the user changes on PANOS, perhaps add new task for commit. 

Cheers

**Comment by Pungyeon** [comment]
I think this feature is pretty important to the philosophy of modern CM tools, so steering away from this is counter-productive in my opinion. I would love to help with the contribution of this, however, I'm thinking we would like to avoid breaking existing installations :) So, guidance on how to proceed would be awesome.

Thanks.

**Comment by shinmog** [comment]
Added in PaloAltoNetworks.paloaltonetworks Ansible Galaxy role version 2.0.x - new `state` of `absent` or `present`.
