### ISSUE TITLE
security_rule module failing

### ISSUE THREAD

**Issue by emaunders** [PaloAltoNetworks/ansible-pan#232]
Hello. 

I am using the following playbook to create a security policy within Panorama:

 - name: Add test pre-rule to Panorama
   panos_security_rule:
     ip_address: ‘{{ panorama_ip_address }}’
     username: ‘{{ panorama_username }}’
     password: ‘{{ panorama_password }}’
     operation: ‘add’
     rule_name: ‘Ansible Test 1’
     description: ‘An Ansible Rest Pre-rule’
     source_zone: [‘DMZ’]
     destination_zone: [‘Internet1’, ‘Internet2’]
     source_ip: [‘1.2.3.4’]
     source_user: [‘any’]
     destination_ip: [‘4.3.2.1’]
     category: [‘any’]
     application: [‘web-browsing’]
     service: [‘service-http’]
     hip_profiles: [‘any’]
     action: ‘allow’
     devicegroup: ‘DeviceGroupA’
     commit: ‘false’

But It is failing with the following error:
fatal: [localhost]: FAILED! => {“changed”: false, “msg”: “Failed \“add\” create: Could not find schema node for xpath /config/shared/rulebase/pre-rulebase/security/rules\n”}

Thanks 
Ed

**Comment by shinmog** [comment]
This should be fixed now.  Please use the most recent Ansible galaxy role:  https://galaxy.ansible.com/PaloAltoNetworks/paloaltonetworks
