### ISSUE TITLE
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

### ISSUE THREAD

**Issue by kshukla-mdn** [PaloAltoNetworks/ansible-pan#244]
-sh-4.2$ sudo ansible-playbook fw_address_group.yml -i inventory.ini --ask-vault-pass
Vault password:
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/home/kshukla/ansible-pan/examples/fw_address_group.yml': line 2, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Add some address groups to the firewall
     hosts: my-firewall
          ^ here

**Comment by trustinger** [comment]
Can you please post the entire playbook and put it in code blocks for formatting purposes?

**Comment by kshukla-mdn** [comment]
`---
- name: Add some address groups to the firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Create static address group
    panos_address_group:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'Prod-Instances'
      static_value: ['Test-1.1.1.1', 'Test-2.2.2.2', 'Test-3.3.3.3']
      tag: ['Prod']

  - name: Create dynamic address group
    panos_address_group:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'SI-Web-EPG'
      dynamic_value: 'SI-Web-EPG'
      tag: ['SI']

  - name: Delete address group
    panos_address_group:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'Old-Prod-Instances'
      state: 'absent'`

**Comment by trustinger** [comment]
You need to add the role otherwise it wont be able to locate the module.
```
- hosts: test_nodes
  connection: local
  roles:
   - role: PaloAltoNetworks.paloaltonetworks
```

**Comment by kshukla-mdn** [comment]
I am still getting same error after adding PaloAlto roles.

===============================
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/home/kshukla/ansible-pan/examples/fw_address_group.yml': line 2, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Add some address groups to the firewall
     hosts: my-firewall
          ^ here
================================================



- name: Add some address groups to the firewall
     hosts: my-firewall
     connection: local
     gather_facts: false
     tasks:
- name: Grab the credentials from ansible-vault
      include_vars: firewall-secrets.yml
      no_log: 'yes'
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

- name: Create static address group
    panos_address_group:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    name: Prod-Instances
    static_value:
      - Test-1.1.1.1
      - Test-2.2.2.2
      - Test-3.3.3.3
    tag:
      - Prod
- name: Create dynamic address group
    Panos_address_group:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    name: SI-Web-EPG
    dynamic_value: SI-Web-EPG
    tag:
      - SI
- name: Delete address group
    panos_address_group:
    ip_address: '{{ ip_address }}'
    username: '{{ username }}'
    password: '{{ password }}'
    name: Old-Prod-Instances
    state: absent
~

**Comment by trustinger** [comment]
Please include it at the top level of the playbook like I posted. Adding it to `include_vars` is going to break it.
```
- hosts: test_nodes
  connection: local
  roles:
   - role: PaloAltoNetworks.paloaltonetworks

  tasks:
```

**Comment by SudarshanVK** [comment]
you can also check if the module is present in the role or Ansible's network module.
ansible-doc -t module <module name>

PS: a few of the modules in the examples here are missing in the role. you may been to wget them manually into the library

**Comment by kshukla-mdn** [comment]
You may be right. Where could I find modules for palo and where should I copy in directory?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SudarshanVK** [comment]
ansible-doc -t module (module name) should give you the path
ansible-pan/library/ has all the libraries.

If you run into any errors, I would first re-download the module from this library and give it a try.

Good Luck. Let me know if you need help. I have been playing around with these modules quite a lot in the recent times.

**Comment by kshukla-mdn** [comment]
thanks. After putting role in playbook issue got resolved.
