### ISSUE TITLE
Feature request: change management interface IP address 

### ISSUE THREAD

**Issue by L1ghtman2k** [PaloAltoNetworks/ansible-pan#246]
Hello!
I was wondering which module should I use to change the management IP address of Palo Alto firewall? From what it seems like panos_interface_module is not responsible for the management interface.

If that is not the case, I think it would be cool if we were able to do that

Thanks!

**Comment by L1ghtman2k** [comment]
This is my solution I tried to implement:
https://github.com/ubnetdef/Lockdown-v7/blob/master/development%20roles/paloalto/library/panos_management_ip_changer.py

It relies on downloading the config, changing the ip_address key in the config, and then re-uploading new config to Palo-Alto, backup your data if you are planning to use it.

**Comment by shinmog** [comment]
@L1ghtman2k 

Right now, I'm thinking that there won't be an Ansible module to change the management interface IP address.

However, now that `panos_type_cmd` exists, you can use that to change it.  If it already has a static IP address set, you just invoke `panos_type_cmd` to set the new IP address.  It should be something like this:

cmd: `set`
xpath: `/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ip-address`
element: `<ip-address>10.1.1.1</ip-address>`
