### ISSUE TITLE
panos_nat_rule destination interface feature

### ISSUE THREAD

**Issue by L1ghtman2k** [PaloAltoNetworks/ansible-pan#253]
Would it be possible to add destination_interface for NAT Plocy rule?
It looks like the current config is missing that feature.

Thanks!

**Comment by dthvt** [comment]
@L1ghtman2k can you try the "to_interface" argument to the module?  It appears to be undocumented, but I think it will do what you want.

**Comment by L1ghtman2k** [comment]
Oh, I see, Thanks! I guess, in that case, it is a documentation request?

**Comment by dthvt** [comment]
If it works correctly for you, yes it's just a doc update.
