### ISSUE TITLE
Using the new json api

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/ansible-pan#263]
I have not used this yet, https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-panorama-api/get-started-with-the-pan-os-rest-api/create-security-policy-rule-rest-api.html but this seems really promising. Is there any thoughts/plan on how to use ansible with this?

**Comment by shinmog** [comment]
Probably not right now.  The new API is not back-ported to (at a minimum in my mind) of 8.0 and 8.1, so we would lose PAN-OS version coverage.  Furthermore, AFAIK the new API itself doesn't have new features to make use of, as it's still in its infancy.
