### ISSUE TITLE
Update modules for v2.1.0

### ISSUE THREAD

**Issue by shinmog** [PaloAltoNetworks/ansible-pan#269]
- [x] panos_address_group.py
- [x] panos_address_object.py
- [x] panos_admin.py
- [x] panos_administrator.py
- [x] panos_admpwd.py
- [x] panos_api_key.py
- [x] panos_bgp.py
- [x] panos_bgp_aggregate.py
- [x] panos_bgp_auth.py
- [x] panos_bgp_conditional_advertisement.py
- [x] panos_bgp_dampening.py
- [x] panos_bgp_peer.py
- [x] panos_bgp_peer_group.py
- [x] panos_bgp_policy_filter.py
- [x] panos_bgp_policy_rule.py
- [x] panos_bgp_redistribute.py
- [x] panos_cert_gen_ssh.py
- [x] panos_check.py
- [x] panos_commit.py
- [x] panos_dag.py
- [x] panos_dag_tags.py
- [x] panos_facts.py
- [x] panos_ike_crypto_profile.py
- [x] panos_ike_gateway.py
- [x] panos_import.py
- [x] panos_interface.py
- [x] panos_ipsec_profile.py
- [x] panos_ipsec_tunnel.py
- [x] panos_lic.py
- [x] panos_loadcfg.py
- [x] panos_loopback_interface.py
- [x] panos_management_profile.py
- [x] panos_match_rule.py
- [x] panos_mgtconfig.py
- [x] panos_nat_rule.py
- [x] panos_object.py
- [x] panos_object_facts.py
- [x] panos_op.py
- [x] panos_pg.py
- [x] panos_query_rules.py
- [x] panos_redistribution.py
- [x] panos_registered_ip.py
- [x] panos_registered_ip_facts.py
- [x] panos_restart.py
- [x] panos_sag.py
- [x] panos_security_rule.py
- [x] panos_service_group.py
- [x] panos_service_object.py
- [x] panos_software.py
- [x] panos_static_route.py
- [x] panos_tag_object.py
- [x] panos_tunnel.py
- [x] panos_userid.py
- [x] panos_virtual_router.py
- [x] panos_zone.py

**Comment by shinmog** [comment]
panos_interface - PR #268

**Comment by shinmog** [comment]
Documentation fragment options:

* panos - Gives `ip_address` / `username` / `password`
* panos.provider - Gives the `provider` dict only
* panos.transitional_provider - Gives both `provider` dict and `ip_address` / `username` / `password` / `api_key` / `port`
* panos.state - Gives `state` param
* panos.rulebase - Gives `rulebase` param
* panos.vsys_dg - Gives `vsys_dg` param (vsys / device group usage)
* panos.device_group - Gives `device_group` param
* panos.vsys_import - Gives `vsys` with default of `None` (for vsys importables:  interfaces, virtual routers, virtual wires, vlans)
* panos.vsys - Gives `vsys` with default of `vsys1` (for non-vsys-importables).
* panos.template_only - Gives `template`
* panos.full_template_support - Gives both `template` and `template_stack`

**Comment by ishuguru** [comment]
You have no idea how glad i am that this project is active again :) 👍

**Comment by dthvt** [comment]
Any chance of getting #271 into 2.1.0?

**Comment by shinmog** [comment]
The following modules will not be updated:

* panos_admpwd
* panos_cert_gen_ssh
* panos_dag_tags
* panos_import
* panos_loadcfg
* panos_object

**Comment by shinmog** [comment]
Role v2.1.0 is now released.
