### ISSUE TITLE
Feature Request: Vlan tag on l2 interface

### ISSUE THREAD

**Issue by ishuguru** [PaloAltoNetworks/ansible-pan#277]
It seems to there is no support for create subinterface/tagged l3 interface at the moment?

**Comment by shinmog** [comment]
@ishuguru 

Not yet.

Subinterfaces need two modules, one for l3, one for l2, so I'm changing this issue to be specific to L2 subinterfaces.

**Comment by shinmog** [comment]
@ishuguru 
For L3 subinterfaces, this is being tracked by the older issue, #194
