### ISSUE TITLE
panos_redistribution - doc issues

### ISSUE THREAD

**Issue by dthvt** [PaloAltoNetworks/ansible-pan#282]
**type** help and doc info says "Name of rule".

Will try to submit a pull request for this shortly, just don't want to forget.

**Comment by dthvt** [comment]
@shinmog - FYI I suspect this will create conflicts w/ the 2.1.0 updates I see you merging, if you get to panos_redistribution before this pull request.

**Comment by shinmog** [comment]
docs should be fixed now, closing this
