### ISSUE TITLE
Feature Request: Allow for static IP configuration on interfaces with panos_interface

### ISSUE THREAD

**Issue by pmusolino-rms** [PaloAltoNetworks/ansible-pan#30]
Being able to set an interface statically from the panos_interface command rather than having to run the verbatim cli command in a config file, load and import would be much appreciated.

**Comment by Gamechiefx** [comment]
Please provide this options so i dont have to use the CLI command to set this up.

**Comment by ivanbojer** [comment]
@shinmog Bump!
