### ISSUE TITLE
Support VPN configuration

### ISSUE THREAD

**Issue by ivanbojer** [PaloAltoNetworks/ansible-pan#31]
Write a module for easy VPN site-to-site configuration.

**Comment by jtschichold** [comment]
:+1:

**Comment by ncse** [comment]
This would be hugely helpful in creating a terraform/ansible demo to show the service vpc architecture.

**Comment by nikmat1** [comment]
VPN is an absolute must have for AWS - please add this functionality ASAP otherwise the whole concept of automation of Transit/Services-VPC falls apart... there is no point in security rules until spoke VPCs are hooked up via VPN.

**Comment by darrenjrogers** [comment]
have been getting requests for this from my customer as well.

**Comment by fallenfuzz** [comment]
BGP setup would also nice in addition to the VPN (mainly for AWS tunnels, but others might also profit)

**Comment by shinmog** [comment]
This has already been fixed for a few releases, with BGP modules now being available.  Closing this generic issue.  Any further issues / requests should use a new github issue.
