### ISSUE TITLE
How to poll on Palo Alto when it Reboots.

### ISSUE THREAD

**Issue by demakkar** [PaloAltoNetworks/ansible-pan#311]
Issue:    How to poll on Palo Alto when it Reboots.below code is failing tp check when device is up after reboot 

fatal: FAILED! => {
    "msg": "The conditional check 'output.stdout[0] is defined and 'yes' not in output.stdout[0]' failed. The error was: error while evaluating conditional (output.stdout[0] is defined and 'yes' not in output.stdout[0]): 'dict object' has no attribute 'stdout'"

 # # Waiting for Authentication Server to become ready
      - name: Wait for Authentication server to be ready
        panos_op:
          ip_address: "{{ inventory_hostname}}"
          username: abc
          password: abc
          cmd: 'show chassis-ready'
        environment:
          PYTHONHTTPSVERIFY: "{{https_verify}}"
        register: output
        until: output.stdout[0] is defined and 'yes' in output.stdout[0]
        retries: 40
        delay: 20

**Comment by shinmog** [comment]
This will be fixed in v2.1.0.  Use `panos_check` with an `initial_delay` of a minute or two.
