### ISSUE TITLE
Unable to attach "antivirus" profile to the security policy

### ISSUE THREAD

**Issue by tush0618** [PaloAltoNetworks/ansible-pan#35]
Hi,

I was trying to attach an already existing **antivirus profile** to a **security** **policy** by using "_panos_security_rule_" module's "**antivirus**" parameter as given at [PaloAlto Ansible Doc](http://docs.ansible.com/ansible/latest/panos_security_rule_module.html#options)

The profile-name of antivirus i.e. **(default)** is getting passed when ansible-playbook is executed (as seen in ansible verbose mode ), but its not getting set to the Palo Alto Dashboard.

Below is the output in verbose mode, after execution of playbook :-

>  "changed": true,
    "invocation": {
        "module_args": {
            "action": "allow",
            **"antivirus": "default",**
            "api_key": null,
            "application": [
                "any"
            ],
            "category": [
                "any"
            ],
            "commit": true,
            "data_filtering": null,
            "description": "Description",
            "destination_ip": [
                "4.2.2.1/32"
            ],
            "destination_zone": [
                "External"
            ],
            "devicegroup": null,
            "file_blocking": null,
            "group_profile": null,
            "hip_profiles": [
                "any"
            ],
            "ip_address": "10.100.100.100",
            "log_end": true,
            "log_start": false,
            "operation": "add",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "rule_name": "Access-List-1",
            "rule_type": "universal",
            "service": [
                "service-https"
            ],
            "source_ip": [
                "10.10.10.1/32"
            ],
            "source_user": [
                "any"
            ],
            "source_zone": [
                "Internal"
            ],
            "spyware": null,
            "tag_name": null,
            "url_filtering": null,
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vulnerability": null,
            "wildfire_analysis": null
        }
    },
    "msg": "Rule 'Access-List-1' successfully added"
}

But its not coming at Dashboard as shown below:

![image](https://user-images.githubusercontent.com/29521446/30808632-8c03a0d2-a21c-11e7-9a89-d6feb7fd5ee0.png)

Below is the existing default antivirus profile: 

![image](https://user-images.githubusercontent.com/29521446/30808798-1ba38036-a21d-11e7-8adb-9c0886656b0b.png)

Can you please check the issue....

Thanks,
Tushar

**Comment by shinmog** [comment]
Closing as per @ivanbojer commit
