### ISSUE TITLE
Undefined dev variable in panos_op

### ISSUE THREAD

**Issue by rvichery** [PaloAltoNetworks/ansible-pan#357]
Recent changes to panos_op introduced by b7d1ecb3d9a8256ed74bed75b3f29002ef809cca are breaking ansible module.
`dev` variable at line 130, https://github.com/PaloAltoNetworks/ansible-pan/commit/b7d1ecb3d9a8256ed74bed75b3f29002ef809cca#diff-4fd57812e780851b0362126e62a77652R130 is not defined.

I will create Pull Request to fix this.

**Comment by rvichery** [comment]
PR #358 fixes this issue. Is there going to be a new ansible galaxy relase soon ?

**Comment by shinmog** [comment]
v2.1.1 is out now with the fix, thanks for the assist
