### ISSUE TITLE
Feature Request: Module for IPv4 Proxy IDs

### ISSUE THREAD

**Issue by odysseus107** [PaloAltoNetworks/ansible-pan#375]
Would love to see an example on how to add a tunnel_monitor_proxy_id (ipv4) with the module panos_ipsec_tunnel

**Comment by shinmog** [comment]
`panos_ipsec_tunnel.tunnel_monitor_proxy_id` is to specify which proxy-id (or proxy-id-v6) to monitoring traffic will use.

If you are asking, "how do I configure one or more (ipv4) Proxy IDs?", then there isn't a module for that yet.

**Comment by odysseus107** [comment]
Okay, thank you for the hint. I changed the title of the request accordingly. It is a feature request then.

**Comment by shinmog** [comment]
Fixed by #380

**Comment by odysseus107** [comment]
Thanks for your help and patience!

**Comment by djfill** [comment]
Hello...I was about to raise a request for this exact issue! Can you share how to use this parameter? I can't see this in the online documentation yet:
https://ansible-pan.readthedocs.io/en/latest/modules/panos_ipsec_tunnel_module.html

**Comment by shinmog** [comment]
@djfill 
That's a different module.  This issue was to add the `panos_ipsec_ipv4_proxyid` module.  This new module (and its documentation) will show up when the role is released.
