### ISSUE TITLE
Feature Request: panos_commit - Commit only changes from a specified user

### ISSUE THREAD

**Issue by ngobert** [PaloAltoNetworks/ansible-pan#401]
In PanOS 8 and above, there is the ability to commit only the changes made by a particular user.  Is it feasible to add this functionality to the panos_commit module as well, using whatever account is specified via the provider/username parameters?

In my case, I'm using an account that is just used for automated configuration, so would like for it be able to commit its own changes without committing any changes that other admins might also be making manually to unrelated parts of the Panorama configuration.

**Comment by shinmog** [comment]
Fixed by #426 by @ngobert - nice work :)
