### ISSUE TITLE
panos_op unconditionally exits with changed=True

### ISSUE THREAD

**Issue by bk2zsto** [PaloAltoNetworks/ansible-pan#406]
Line 140 statically assigns _True_ to **changed** and no other place in the module refers to it.

Since only **_set_** will come close to changing config and I am guessing **_configure_** is rejected should this module default to _False_ for **changed**?

**Comment by shinmog** [comment]
`type=op` commands are capable of affecting change on firewalls.  For example, both downloading and installing software are both op commands.  So `panos_op` does return changed=True unconditionally because it has no idea as to the nature of the command that is has executed.
