### ISSUE TITLE
multiple traceback failures - xapi,  generate_xapi, _apikey, show_system_info, create_from_device

### ISSUE THREAD

**Issue by DevGumbo** [PaloAltoNetworks/ansible-pan#409]
TASK [permit ssh to 1.1.1.1] ************************************************************************************************************************************************************************************
task path: /home/ansible/local_ansible/playbook_set_srule.yml:32
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<127.0.0.1> EXEC /bin/sh -c 'echo ~ansible && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560 `" && echo ansible-tmp-1561673400.87-261648118461560="` echo /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560 `" ) && sleep 0'
Using module file /home/ansible/.ansible/roles/PaloAltoNetworks.paloaltonetworks/library/panos_security_rule.py
<127.0.0.1> PUT /home/ansible/.ansible/tmp/ansible-local-26682ZrGGVJ/tmpaGCmUZ TO /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560/AnsiballZ_panos_security_rule.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560/ /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560/AnsiballZ_panos_security_rule.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/ansible/local_ansiblepy/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560/AnsiballZ_panos_security_rule.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1561673400.87-261648118461560/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_panos_security_rule_payload_jy5H5F/ansible_panos_security_rule_payload.zip/ansible/module_utils/network/panos/panos.py", line 137, in get_pandevice_parent
    self.device = PanDevice.create_from_device(*pan_device_auth)
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3336, in create_from_device
    system_info = device.refresh_system_info()
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3744, in refresh_system_info
    system_info = self.show_system_info()
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3701, in show_system_info
    root = self.xapi.op(cmd="show system info", cmd_xml=True)
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3566, in xapi
    self._xapi_private = self.generate_xapi()
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3608, in generate_xapi
    kwargs = {'api_key': self.api_key,
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3560, in api_key
    self._api_key = self._retrieve_api_key()
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3694, in _retrieve_api_key
    xapi.keygen(retry_on_peer=False)
  File "/home/ansible/local_ansiblepy/local/lib/python2.7/site-packages/pandevice/base.py", line 3462, in method
    raise the_exception

It will not go all the way through and connect no matter how many times i have tweaked it.

Please help!

**Comment by DevGumbo** [comment]
TASK [permit ssh to 1.1.1.1] ************************************************************************************************************************************************************************************
task path: /home/ansible/local_ansible/playbook_set_srule.yml:33
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<127.0.0.1> EXEC /bin/sh -c 'echo ~ansible && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1561674368.11-73118559799192 `" && echo ansible-tmp-1561674368.11-73118559799192="` echo /home/ansible/.ansible/tmp/ansible-tmp-1561674368.11-73118559799192 `" ) && sleep 0'
Using module file /home/ansible/.ansible/roles/PaloAltoNetworks.paloaltonetworks/library/panos_security_rule.py
<127.0.0.1> PUT /home/ansible/.ansible/tmp/ansible-local-29566auQ6wr/tmpvg5pge TO /home/ansible/.ansible/tmp/ansible-tmp-1561674368.11-73118559799192/AnsiballZ_panos_security_rule.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1561674368.11-73118559799192/ /home/ansible/.ansible/tmp/ansible-tmp-1561674368.11-73118559799192/AnsiballZ_panos_security_rule.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/ansible/local_ansiblepy/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1561674368.11-73118559799192/AnsiballZ_panos_security_rule.py && sleep 0'

**Comment by DevGumbo** [comment]
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "allow",
            "antivirus": null,
            "api_key": null,
            "application": [
                "ssh"
            ],
            "category": [
                "any"
            ],
            "commit": false,
            "data_filtering": null,
            "description": "SSH rule test",
            "destination_ip": [
                "1.1.1.1"
            ],
            "destination_zone": [
                "trust"
            ],
            "device_group": "shared",
            "devicegroup": null,
            "disable_server_response_inspection": false,
            "disabled": false,
            "existing_rule": null,
            "file_blocking": null,
            "group_profile": null,
            "hip_profiles": [
                "any"
            ],
            "icmp_unreachable": null,
            "ip_address": "192.168.168.168",
            "location": null,
            "log_end": true,
            "log_setting": null,
            "log_start": false,
            "negate_destination": false,
            "negate_source": false,
            "negate_target": null,
            "operation": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "provider": null,
            "rule_name": "SSH permit",
            "rule_type": "universal",
            "rulebase": null,
            "schedule": null,
            "service": [
                "application-default"
            ],
            "source_ip": [
                "any"
            ],
            "source_user": [
                "any"
            ],
            "source_zone": [
                "untrust"
            ],
            "spyware": null,
            "state": "present",
            "tag_name": null,
            "target": null,
            "url_filtering": null,
            "username": "pan_user_name",
            "vsys": "vsys1",
            "vulnerability": null,
            "wildfire_analysis": null
        }
    },
    "msg": "Failed connection: URLError: reason: [Errno 110] Connection timed out"
}

**Comment by shinmog** [comment]
@DevGumbo 
Seems it's a connection issue.  Can you verify that you are giving the correct IP address / username / password values?  Based on that output, I can see you're doing:

```yaml
ip_address: '192.168.168.168'
username: 'pan_user_name'
password: (value isn't being logged, so whatever you are specifying)
```

**Comment by DevGumbo** [comment]
Yes thank you. It was related to a firewall rule not allowing ssh/ssl.
This issue is resolved now.
