### ISSUE TITLE
panos_mgtconfig - Error when attempting to set NTP primary and secondary server

### ISSUE THREAD

**Issue by smatt241** [PaloAltoNetworks/ansible-pan#41]
failed: [192.168.77.250 -> localhost] (item={u'primary': u'3.3.3.3', u'secondary': u'4.4.4.4'}) => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "commit": "False",
            "ip_address": "192.168.77.250",
            "ntp_server_primary": "3.3.3.3",
            "ntp_server_secondary": "4.4.4.4",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "item": {
        "primary": "3.3.3.3",
        "secondary": "4.4.4.4"
    },
    "msg": "Unsupported parameters for (panos_mgtconfig) module: ntp_server_primary,ntp_server_secondary Supported parameters include: commit,dns_server_primary,dns_server_secondary,ip_address,panorama_primary,panorama_secondary,password,username"
}

**Comment by ivanbojer** [comment]
This issue should be fixed by now. Please re-open if you still see the issue in the latest version.
