### ISSUE TITLE
panos_security_rule | state attribute

### ISSUE THREAD

**Issue by SudarshanVK** [PaloAltoNetworks/ansible-pan#410]
State: "present" overwrites any existing rule with the same name which may be undesirable. Is there a way to back out if the rule name already exists or is that a login I will need to build into my script?

Can the operation feature be brought back?

**Comment by shinmog** [comment]
Use `panos_security_rule_facts` to get the list of security rules, then a subsequent `panos_security_rule` task can have a `when:` specification that prevents the task from running if the name is already present.
