### ISSUE TITLE
Setting create_default_route and enable_dhcp to False does not work in panos_interface

### ISSUE THREAD

**Issue by AmGeorgiou** [PaloAltoNetworks/ansible-pan#411]
This issue seems to be a variant of #229 and #247.

In our case, if we omit the `create_default_route` (should default to `False`) or pass `create_default_route=False`, the option to "Automatically create default route" is not disabled.

PR to follow with proposed fix.

Seeing as similar (although distinctly different!) fixes have been applied before and then reverted, if the proposed fix is not suitable, could you please look into providing a permanent fix (perhaps outside of reading the module args into the spec)?

**Comment by shinmog** [comment]
`panos_interface` is weird, and the XML schema seems to actively work against you at that location, which is why there is code continually making changes thinking it knows what it's doing, and then another change after that.

I'll leave more specific comments on your PR.

**Comment by AmGeorgiou** [comment]
Thanks @shinmog. I have proposed a slightly different logic and added the details on the PR as well.

Let me know what you think.

**Comment by shinmog** [comment]
Fixed by #412
