### ISSUE TITLE
Error with IKE Gateway peer-id-type and peer-id-value when using PSK

### ISSUE THREAD

**Issue by dailejc** [PaloAltoNetworks/ansible-pan#416]
When configuring an IKE Gateway using PSK Auth, you cant set the peer-id-type or peer-id-value without it requiring a peer-id-check type. Peer id check is used for cert based auth, not PSK. I tried removing the check for those three together locally to see if it would insert those values anyway, but it doesnt. Local-id-type and local-id-value are fine and they set as expected. Seems like there should be a authentication-type setting to specify pre-shared key or certificate first, then set the peer-id type and value (or check type if certificate is selected)

**Comment by dailejc** [comment]
I should add we use FQDN type peer ids

**Comment by bk2zsto** [comment]
Confirmed also with PSK and peer_id_type = ipaddr
