### ISSUE TITLE
panos_object - Error when attempting to set tag color

### ISSUE THREAD

**Issue by smatt241** [PaloAltoNetworks/ansible-pan#42]
The full traceback is:
  File "/tmp/ansible_Nw_VUh/ansible_module_panos_object.py", line 426, in main
    changed = add_object(device, dev_group, new_object)
  File "/tmp/ansible_Nw_VUh/ansible_module_panos_object.py", line 281, in add_object
    new_object.create()
  File "/usr/local/lib/python2.7/dist-packages/pandevice/base.py", line 542, in create
    device.active().xapi.set(self.xpath_short(), element, retry_on_peer=self.HA_SYNC)
  File "/usr/local/lib/python2.7/dist-packages/pandevice/base.py", line 3098, in method
    raise the_exception

failed: [192.168.77.250 -> localhost] (item={u'colour': u'orange', u'name': u'test3'}) => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "address": null,
            "address_type": "ip-netmask",
            "addressgroup": null,
            "addressobject": null,
            "api_key": null,
            "color": "orange",
            "description": null,
            "destination_port": null,
            "devicegroup": null,
            "dynamic_value": null,
            "ip_address": "192.168.77.250",
            "operation": "add",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": null,
            "servicegroup": null,
            "serviceobject": null,
            "services": null,
            "source_port": null,
            "static_value": null,
            "tag_name": "test3",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "item": {
        "colour": "orange",
        "name": "test3"
    },
    "msg": " test3 -> color 'orange' is not an allowed keyword\n test3 -> color is invalid"
}

**Comment by shinmog** [comment]
There is a `pandevice.objects.Tag.color_code()` static method that takes in a color and returns the actual color string to be used.  The code should be changed from this:

```
        newobject = objects.Tag(
            name=kwargs['tag_name'],
            color=kwargs['color'],
            comments=kwargs['description']
        )
```

...to this:
```
        newobject = objects.Tag(
            name=kwargs['tag_name'],
            comments=kwargs['description']
        )
        newobject.color = newobject.color_code(kwargs['color'])
```

**Comment by merewind** [comment]
folks, any updates on if this will be corrected?

**Comment by ivanbojer** [comment]
V1.0.7
