### ISSUE TITLE
Setting some Panos_mgtconfig items deletes large sections of pre-existing configuration that cant' be repaired with mgtconfig

### ISSUE THREAD

**Issue by M3chanik** [PaloAltoNetworks/ansible-pan#431]
Hey folks,

I ran into an issue with the following.  I try to add some very basic settings over a playbook that looks like the following:

>  - name: Set ntp and dns but don't commit
>     panos_mgtconfig:
>       provider: "{{ providerinfo }}"
>       dns_server_primary: "10.XXX.XXX.1"
>       dns_server_secondary: "10.XXX.XXX.2"
>       ntp_server_primary: "10.XXX.XXX.3"
>       ntp_server_secondary: "10.XXX.XXX.4"
>       commit: False
>     register: response

This adds the modifications, but blows away snmp settings, update settings etc.  They would have looked like the following.

> update-schedule {
> 		anti-virus {
> 	  		recurring {
> 		  		daily {
> 				  	at 01:00;
> 				  	action download-and-install;
> 			  	}
> 		  		threshold 4;
> 			  	sync-to-peer yes;
> 			}
> 	  	}
> 	  	threats {
> 		  	recurring {
> 			  	threshold 4;
> 				new-app-threshold 4;
> 				sync-to-peer yes;
> 				weekly {
> 				  	at 01:02;
> 				  	day-of-week wednesday;
> 				  	action download-and-install;
> 			  	}
> 			}
> 	  	}
> snmp-setting {
> 	access-setting {
> 	  	version {
> 		  	v2c {
> 			  	snmp-community-string XXXXXXXXXXXXX;
> 	  		}
> 	  	}
> 	}
> 	snmp-system {
> 		location San Francisco;
> 

Shouldn't these settings be able to be set within the panos_mgtconfig module?  Can that functionality be added?

Thanks!
Brian

**Comment by shinmog** [comment]
I think this is happening because pandevice may not know everything that is possibly configured, and this cannot keep the config settings before doing `obj.apply()`.  I think this module will need to be changed to do one API call per variable changed, ensuring it only touches that one param, instead of applying the entire system config.
