### ISSUE TITLE
panos_interface tcp port not override

### ISSUE THREAD

**Issue by iarnopagliani** [PaloAltoNetworks/ansible-pan#435]
## Describe the bug
It seems that the TCP port connection 443 is fixed; I'm not able to change it.
I'm using provider variable:
provider:
  api_key: "mykey"
  ip_address: "{{ ansible_host }}"
  port: "{{ ansible_port }}"
and 
ansible_port: "1234" in inventory file.
Same with: port: "1234"

But in capture file is still 443.

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by shinmog** [comment]
@iarnopagliani 

I can't reproduce this.  My firewall is listening on 443, and when I configure my provider dict with `port: 1234`, I get the following:

```base
TASK [Configure system settings (checkmode)] ********************************************************************************
fatal: [10.8.202.114]: FAILED! => {"changed": false, "msg": "Failed connection: URLError: reason: [Errno 60] Operation timed out"}
```

When I configure my provider dict with `port: 443`, it works:

```bash
TASK [Configure system settings (checkmode)] ********************************************************************************
ok: [10.8.202.114]
```

Seems something is wrong in your environment..?

**Comment by shinmog** [comment]
This seems to be resolved, aging this issue out.
