### ISSUE TITLE
panos_static_route broken: 'ConnectionHelper' object has no attribute 'apply_state'

### ISSUE THREAD

**Issue by calltomdinesh** [PaloAltoNetworks/ansible-pan#439]
Seeing below error while using panos_static_route module.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'ConnectionHelper' object has no attribute 'apply_state'

fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1572933157.85-280592588763105/AnsiballZ_panos_static_route.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1572933157.85-280592588763105/AnsiballZ_panos_static_route.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1572933157.85-280592588763105/AnsiballZ_panos_static_route.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_static_route_payload_mG2gGW/__main__.py\", line 214, in <module>\n  File \"/tmp/ansible_panos_static_route_payload_mG2gGW/__main__.py\", line 208, in main\nAttributeError: 'ConnectionHelper' object has no attribute 'apply_state'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I have used ansible module as below:

panos_static_route:
    provider: '{{ panos_provider }}'
    name: 'Test-One'
    destination: '10.x.x.x/28'
    nexthop: '10.x.x.x'
    template: "{{panos_template}}"
    virtual_router: "{{panos_vr_name}}"
    state: 'present'

## Describe the bug

seeing the error "An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'ConnectionHelper' object has no attribute 'apply_state'" while using panos_static_route module

## Expected behavior

Static route has to be created properly

## Current behavior

seeing the error "An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'ConnectionHelper' object has no attribute 'apply_state'" while using panos_static_route module

## Steps to reproduce

Not sure. apply_state mehod exists in panos.py

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by shinmog** [comment]
@calltomdinesh 

Try updating your panos role.  `apply_state()` was added to the panos role back in March, so you seem to be running very old code.

**Comment by calltomdinesh** [comment]
Thanks, It works.

**Comment by shinmog** [comment]
Glad it works for you now :)

Resolving this issue.
