### ISSUE TITLE
Revert to Previous Commit or particular commit

### ISSUE THREAD

**Issue by mohamedshafiq** [PaloAltoNetworks/ansible-pan#442]
Hi Team,

I would like to revert to previous or particular commit in Palo Alto when a configuration play get failed. Is there any module available for reverting to previous commit or particular commit. Please help with this.

**Comment by megakoresh** [comment]
> Hi Team,
> 
> I would like to revert to previous or particular commit in Palo Alto when a configuration play get failed. Is there any module available for reverting to previous commit or particular commit. Please help with this.

Set `commit: false` on every task and commit separately at the end of the playbook. This way it has the same effect. I don't understand why `commit` is true by default, doesn't make any sense to me, but this is the better way to attain your desired outcome.

**Comment by mohamedshafiq** [comment]
if we set commit false it doesn't revert the changes what has been executed during the play before failure. the changes are still available. So now i have implemented block and rescue module in the playbook if any play fails it will revert to the running configuration of the firewall whether this implementation is fine or any other suggestions.

**Comment by mrichardson03** [comment]
This can be done with the `panos_op` module and the `revert config` command.
