### ISSUE TITLE
Not able to see Pan os operational command output in standard understanding format

### ISSUE THREAD

**Issue by naveenkumarr91j** [PaloAltoNetworks/ansible-pan#453]
When i am running this task below iam not getting output in standard understanding format

  - name: Commit pending firewall changes
     panos_op:
       cmd: 'show system software status'
       provider: '{{ connection }}'
     register: result1

   - debug: msg='{{ (result1.stdout | from_json)['response']['result'] }}'

TASK [debug] ***********************************************************************************************************************************************************************************
ok: [PA] => {
    "msg": "Slot 1, Role mp\n----------------------------------------\n\nType     Name                 State    Info\nGroup    all                  running  \nGroup    base                 running  \nGroup    batch                running  \nGroup    chassis              running  \nGroup    data_plane           running  \nGroup    dsms                 running  \nGroup    gdb                  running  \nGroup    ha_ssh               running  \nGroup    mgmt_services        running  \nGroup    ntlm-grp             running  \nGroup    services             running  \nGroup    supervisor           running  \nGroup    tasks                running  \nGroup    third_party          running  \nProcess  acpid                running  (pid: 2200) \nProcess  all_task             running  (pid: 2774) \nProcess  appweb               running  (pid: 2899) \nProcess  authd                running  (pid: 2916) \nProcess  bfd                  running  (pid: 2830) \nProcess  brdagent             running  (pid: 2263) \nProcess  chasd                running  (pid: 2222) \nProcess  comm                 running  (pid: 2771) \nProcess  crypto               running  (pid: 2595) \nProcess  dagger               running  (pid: 2197) \nProcess  devsrvr              running  (pid: 2819) \nProcess  dha                  running  (pid: 2914) \nProcess  dhcp                 running  (pid: 2911) \nProcess  dnsproxy             running  (pid: 2912) \nProcess  ehmon                running  (pid: 2221) \nProcess  ha-sshd              running  (pid: 2663) \nProcess  ha_agent             running  (pid: 2908) \nProcess  ikemgr               running  (pid: 2902) \nProcess  keymgr               running  (pid: 2905) \nProcess  l2ctrl               running  (pid: 2907) \nProcess  l3svc                running  (pid: 6697) \nProcess  logrcvr              running  (pid: 2903) \nProcess  masterd              running  (pid: 2107) \nProcess  mgmtsrvr             running  (pid: 2855) \nProcess  monitor              running  (pid: 2198) \nProcess  monitor-dp           running  (pid: 2982) \nProcess  mprelay              running  (pid: 2831) \nProcess  pppoe                running  (pid: 2913) \nProcess  rasmgr               running  (pid: 2904) \nProcess  routed               running  (pid: 2915) \nProcess  satd                 running  (pid: 2909) \nProcess  snmpd                running  (pid: 2917) \nProcess  sshd                 running  (pid: 2687) \nProcess  sslmgr               running  (pid: 2910) \nProcess  sslvpn               running  (pid: 2901) \nProcess  sslvpn_ngx           running  (pid: 2927) \nProcess  sysd                 running  (pid: 2142) \nProcess  sysdagent            running  (pid: 2203) \nProcess  tund                 running  (pid: 2832) \nProcess  useridd              running  (pid: 2822) \nProcess  varrcvr              running  (pid: 2906) \nProcess  vm_agent             running  (pid: 2199) \nProcess  websrvr              running  (pid: 2896)"
}

but output iam expecting as below because in Paloalto firewall we are getting in this format for understandable one.

admin@PA-VM> show system software status

Slot 1, Role mp
----------------------------------------

Type     Name                 State    Info
Group    all                  running
Group    base                 running
Group    batch                running
Group    chassis              running
Group    data_plane           running
Group    dsms                 running
Group    gdb                  running
Group    ha_ssh               running
Group    mgmt_services        running
Group    ntlm-grp             running
Group    services             running
Group    supervisor           running
Group    tasks                running
Group    third_party          running
Process  acpid                running  (pid: 2200)
Process  all_task             running  (pid: 2774)
Process  appweb               running  (pid: 2899)
Process  authd                running  (pid: 2916)
Process  bfd                  running  (pid: 2830)
Process  brdagent             running  (pid: 2263)
Process  chasd                running  (pid: 2222)
Process  comm                 running  (pid: 2771)
Process  crypto               running  (pid: 2595)
Process  dagger               running  (pid: 2197)
Process  devsrvr              running  (pid: 2819)
Process  dha                  running  (pid: 2914)
Process  dhcp                 running  (pid: 2911)
Process  dnsproxy             running  (pid: 2912)
Process  ehmon                running  (pid: 2221)
Process  ha-sshd              running  (pid: 2663)
Process  ha_agent             running  (pid: 2908)
Process  ikemgr               running  (pid: 2902)
Process  keymgr               running  (pid: 2905)
Process  l2ctrl               running  (pid: 2907)
Process  l3svc                running  (pid: 6697)
Process  logrcvr              running  (pid: 2903)
Process  masterd              running  (pid: 2107)
Process  mgmtsrvr             running  (pid: 2855)
Process  monitor              running  (pid: 2198)
Process  monitor-dp           running  (pid: 2982)
Process  mprelay              running  (pid: 2831)
Process  pppoe                running  (pid: 2913)
Process  rasmgr               running  (pid: 2904)
Process  routed               running  (pid: 2915)
Process  satd                 running  (pid: 2909)
Process  snmpd                running  (pid: 2917)
Process  sshd                 running  (pid: 2687)
Process  sslmgr               running  (pid: 2910)
Process  sslvpn               running  (pid: 2901)
Process  sslvpn_ngx           running  (pid: 2927)
Process  sysd                 running  (pid: 2142)
Process  sysdagent            running  (pid: 2203)
Process  tund                 running  (pid: 2832)
Process  useridd              running  (pid: 2822)
Process  varrcvr              running  (pid: 2906)
Process  vm_agent             running  (pid: 2199)
Process  websrvr              running  (pid: 2896)

Need help on this as for performing operational command using ansible for paloalto will be difficult with this kind of nonstandard format output.

Iam using below ansible version in Ubuntu 16 .04.2 LTS

ansible 2.9.2
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]

------------------------

NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by shinmog** [comment]
@naveenkumarr91j 

You are getting exactly what you want, just some additional information up front as a header.

The extra characters (all the `\n` you're seeing) is Ansible rendering the newlines separating the data that you get in the CLI as a newline character instead of a visual newline.
