### ISSUE TITLE
panos_query_rules module is unavailable

### ISSUE THREAD

**Issue by Seethaar** [PaloAltoNetworks/ansible-pan#46]
I wanted to try some modules to check the config on palo alto firewalls, before trying the action modules like panos_lic. There are only two such modules that I see on http://panwansible.readthedocs.io/en/latest/modules.html

panos_check
panos_query_rules

I don't see panos_query_rules on,

https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/network/panos

Could you please tell me where can I avail that?

Thanks.

**Comment by ivanbojer** [comment]
If you use paloaltonetworks role you will be fine. The reason why you don't see this -- yet -- in the official ansible library is due to the release process and Ansible. It should be in as of next Ansible release.
