### ISSUE TITLE
panos_ike_gateway needs dynamic/FQDN peer address support

### ISSUE THREAD

**Issue by odysseus107** [PaloAltoNetworks/ansible-pan#465]
In Palo Alto -> IKE Gateways you can set the "Peer IP Address Type" to 

- IP
- FQDN
- Dynamic

Only IP is currently implemented, the other options are not yet available in the library.

**Comment by shinmog** [comment]
As mentioned [here](https://github.com/PaloAltoNetworks/ansible-pan/issues/464), this role is now deprecated in favor of the collection.  Could you open up this feature request as a github issue against the collection?

Just curious, but have you updated to Ansible 2.9 yet, @odysseus107 ?

**Comment by odysseus107** [comment]
> Just curious, but have you updated to Ansible 2.9 yet, @odysseus107 ?

No, not yet

**Comment by odysseus107** [comment]
Now we switched to Ansible 2.9.5 and the PAN-OS Ansible Collection. Our status quo seems to work after this migration. Keep an eye on that :)

**Comment by mrichardson03** [comment]
Partially fixed in https://github.com/PaloAltoNetworks/pan-os-ansible/issues/10.
