### ISSUE TITLE
[request] active sessions manipulations

### ISSUE THREAD

**Issue by fallenfuzz** [PaloAltoNetworks/ansible-pan#484]
kindly add possibility to
 - show active sessions with filters
 - clear active sessions with filters

Thanks

**Comment by mrichardson03** [comment]
**Please note**, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection and no new features will be added to it.  Please consider opening issues against the [collection](https://github.com/PaloAltoNetworks/pan-os-ansible) instead.

These are operational commands, which can be performed with `panos_op`.
