### ISSUE TITLE
panso_op result query or filtering

### ISSUE THREAD

**Issue by jacquen** [PaloAltoNetworks/ansible-pan#497]
Hi, 

I trying to filtering some result from panos_op module outpout, I can use json_query query to first level of result, like msg or stdout, but I cannot go further, anyone can give some suggestion how to query in deep? 

my expect result will be get MAC address: "mac": "34:e5:ec:65:15:10"

Thanks

=================================
My playbook like this:
- name: This playbook for download software to PA
  hosts: batch1
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: check OS and download
      block:

        - name: check os 1st time
          panos_op:
            provider: '{{ login_info }}'
            cmd: "show interface ethernet1/1"
          register: getresult

        - name: filter
          debug:
            msg="{{ getresult | json_query(jme) }}"
          vars:
            jme: "stdout"

================================
my result like this:

ok: [FW01-850] => {
    "getresult": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python3"
        },
        "changed": false,
        "failed": false,
        "msg": "Done",
        "stdout": "{\"response\": {\"@status\": \"success\", \"result\": {\"ifnet\": {\"addr6\": null, \"tag\": \"0\", \"circuitonly\": \"False\", \"ndpmon\": \"False\", \"id\": \"16\", \"mgt_subnet\": \"False\", \"addr\": null, \"service\": null, \"ra\": \"False\", \"zone\": \"N/A\", \"counters\": {\"ifnet\": {\"entry\": {\"icmp_frag\": \"0\", \"ifwderrors\": \"0\", \"ierrors\": \"0\", \"macspoof\": \"0\", \"pod\": \"0\", \"flowstate\": \"0\", \"ipspoof\": \"0\", \"teardrop\": \"0\", \"ibytes\": \"21663\", \"noarp\": \"0\", \"sctp_conn\": \"0\", \"noroute\": \"0\", \"noneigh\": \"0\", \"nomac\": \"0\", \"l2_encap\": \"0\", \"zonechange\": \"0\", \"other_conn\": \"0\", \"obytes\": \"0\", \"land\": \"0\", \"name\": \"ethernet1/1\", \"tcp_conn\": \"0\", \"neighpend\": \"0\", \"ipackets\": \"72\", \"opackets\": \"0\", \"l2_decap\": \"0\", \"udp_conn\": \"0\", \"idrops\": \"0\"}}, \"hw\": {\"entry\": {\"obytes\": \"0\", \"name\": \"ethernet1/1\", \"idrops\": \"0\", \"ipackets\": \"72\", \"opackets\": \"0\", \"ierrors\": \"0\", \"ibytes\": \"21663\", \"port\": {\"tx-unicast\": \"0\", \"tx-multicast\": \"0\", \"rx-broadcast\": \"0\", \"rx-unicast\": \"6\", \"rx-multicast\": \"66\", \"rx-bytes\": \"21951\", \"tx-broadcast\": \"0\", \"tx-bytes\": \"0\"}}}}, \"dad\": \"False\", \"policing\": \"False\", \"mssadjv4\": \"0\", \"mssadjv6\": \"0\", \"fwd_type\": \"vwire\", \"name\": \"ethernet1/1\", \"tunnel\": null, \"vsys\": \"vsys1\", \"dyn-addr\": null, \"vwire\": \"default-vwire\", \"tcpmss\": \"False\", \"mode\": \"virtual-wire\", \"vw_peer\": \"ethernet1/2\"}, \"hw\": {\"untag\": \"False\", \"name\": \"ethernet1/1\", \"duplex\": \"unknown\", \"type\": \"0\", \"state_c\": \"auto\", \"mac\": \"34:e5:ec:65:15:10\", \"state\": \"down\", \"duplex_c\": \"auto\", \"mode\": \"virtual-wire\", \"speed_c\": \"auto\", \"link\": \"False\", \"speed\": \"unknown\", \"id\": \"16\", \"down_passthru\": \"True\"}, \"dp\": \"dp0\"}}}",

**Comment by mrichardson03** [comment]
**Please note**, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection and no new features will be added to it.  Please consider opening issues against the [collection](https://github.com/PaloAltoNetworks/pan-os-ansible) instead.

You'll need to utilize the the `from_json` filter to convert the JSON text into a dict data structure, then query it per the [JSON Query Filter](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter) documentation.

Your playbook step should be:

```
- debug:
    msg: "{{ getresult | from_json | json_query('response.result.hw.mac') }}"
```
