### ISSUE TITLE
Question: panos_loadcfg

### ISSUE THREAD

**Issue by jedelman8** [PaloAltoNetworks/ansible-pan#5]
There isn't too much commentary in the docstring, so a few questions:
- Does panos_loadcfg do a full config replace and only apply the diffs required to get the device into its desired state?
- Does the `file` param need to point to a FULL config file? Can we send a partial config?
- What format does the config need to be in?  Are there options such as curly brace, set notation, XML, etc.?
- It doesn't look like this module supports check_mode.  Can you confirm?
- It looks like it's idempotent based on the last conditional in the module. Can you confirm?

**Comment by jtschichold** [comment]
Hi Jason,
- panos_loadcfg can be used to load as the device canidate config a configuration file already imported on the PAN-OS using the "load config" PAN-OS API. The "load config" API replaces the whole candidate config with the contents of the local file. If the _commit_ is set to True, after the new candidate config has been loaded the module commits the config. PAN-OS **commit** op takes care of applying the diffs between the _candidate_ config and the _running_ config.
- The _file_ parameter is set to the name of the device local config that should be loaded
- Configs are stored and loaded in XML. set notation is more human readable but it is not 100% reliable when it comes to backup & restore operations.
- You are right, no check_mode yet
- The last check is always True, we have plans to implement a double check if something has changed before the load but this has not been done yet. It is also true that during a commit PAN-OS itself checks if candidate and running configs differ, and only in that case the diff is applied.

**Comment by jedelman8** [comment]
Thank you! One more for now. Do you return the diffs that are being applied? If not, should it be possible if we want to add that functionality?

**Comment by jtschichold** [comment]
No, diffs are not returned. But it should be possible as PAN-OS offers an XML API for that ("diff config").

**Comment by jedelman8** [comment]
Thanks you.
