### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by ismc** [PaloAltoNetworks/ansible-pan#50]
I keep getting "SSL: CERTIFICATE_VERIFY_FAILED" when running panos_interface.  Is there a way to disable certificate validation?

Thanks,

Steven.

- name: configure ethernet1/1 for DHCP
      panos_interface:
        ip_address: "{{ ansible_host }}"
        password: "{{ network_password }}"
        if_name: "ethernet1/1"
        zone_name: "untrust"
        create_default_route: "yes"
        commit: False

TASK [configure ethernet1/1 for DHCP] ************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pan.xapi.PanXapiError: URLError: reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
fatal: [smc_pan_demo1_rtr]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_HsidFQ/ansible_module_panos_interface.py\", line 184, in <module>\n    main()\n  File \"/tmp/ansible_HsidFQ/ansible_module_panos_interface.py\", line 167, in main\n    ifexists = if_exists(xapi, if_name)\n  File \"/tmp/ansible_HsidFQ/ansible_module_panos_interface.py\", line 133, in if_exists\n    xapi.get(xpath=xpath)\n  File \"/usr/lib/python2.7/site-packages/pan/xapi.py\", line 727, in get\n    self.__type_config('get', query, extra_qs)\n  File \"/usr/lib/python2.7/site-packages/pan/xapi.py\", line 789, in __type_config\n    self.__set_api_key()\n  File \"/usr/lib/python2.7/site-packages/pan/xapi.py\", line 583, in __set_api_key\n    self.keygen()\n  File \"/usr/lib/python2.7/site-packages/pan/xapi.py\", line 637, in keygen\n    raise PanXapiError(self.status_detail)\npan.xapi.PanXapiError: URLError: reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by ivanbojer** [comment]
Yes, there is. Please add this to your environment:
export PYTHONHTTPSVERIFY=0

**Comment by dfitz82** [comment]
What's the proper way to request to re-opened and add an option to validate certs or not.  I realize PEP 493 sets the environment variable, however my ansible server must support connections where certificates are being validated using python.  To keep the ansible modules running smoothly I am having to hit the API directly and avoid using ansible-pan moduels, which is not ideal.

**Comment by stobias123** [comment]
@ivanbojer  - this workaround enables me to execute my playbook, but this isn't really acceptable as a solution from a firewall vendor is it?

I'm gonna echo dfitz82 here that at minimum it should be a module option, so we don't have to set this globally in shared execution environments.

**Comment by mlowcher61** [comment]
That env var did not work for me.
