### ISSUE TITLE
Can we create Application Group using the Ansible modules?

### ISSUE THREAD

**Issue by karkisai** [PaloAltoNetworks/ansible-pan#500]
**Please note**, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection and no new
features will be added to it.  Please consider opening issues against the
[collection](https://github.com/PaloAltoNetworks/pan-os-ansible) instead.

**Comment by mrichardson03** [comment]
Please note, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection and no new
features will be added to it. Please consider opening issues against the
collection instead.
