### ISSUE TITLE
Which of the two competing repositories by Palo Alto Networks should I use?

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [PaloAltoNetworks/ansible-pan#501]
https://github.com/PaloAltoNetworks/pan-os-ansible/ or https://github.com/PaloAltoNetworks/ansible-pan

- Both seem to be maintained by Palo Alto Networks, Inc
- Both seem to be up-to-date (July 2020 and Sept 2020)
- Neither mentions in any of their docs which one to use.

**Comment by krestivo-kdinfotech** [comment]
See https://github.com/PaloAltoNetworks/pan-os-ansible/issues/100

**Comment by stealthllama** [comment]
The pan-os-ansible repo is the most current and is being used to publish the PAN-OS Ansible collection on Galaxy. The legacy ansible-pan repo will be retired once Galaxy is able to render the collection and module documentation (supposedly in beta testing now).

**Comment by mrichardson03** [comment]
The reader clearly states:

Please note, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection and no new features will be added to it. Please begin using the Ansible collection instead.
