### ISSUE TITLE
panos_ipsec_tunnel anti_replay option doesn't work

### ISSUE THREAD

**Issue by tedolin** [PaloAltoNetworks/ansible-pan#502]
**Please note**, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection
and no new features will be added to it.  Please consider opening issues against the 
[collection](https://github.com/PaloAltoNetworks/pan-os-ansible) instead.

## Describe the bug
When I setup or modify an ipsec tunnel, using panos_ipsec_tunnel module, there's option "anti_replay" which enables or disables the Replay Protection option for the tunnel. It's default action is to enable it, but when I want to disable the option for a tunnel, it doesn't work. It seems that Ansible get's the assigned value correctly, but for some reason, the candidate configuration always contains <anti-replay>yes</anti-replay> to be applied to the device. 

## Expected behavior

When I set:
 - name: Example task
   panos_ipsec_tunnel:
      anti_replay: no 

or 

 - name: Example task
   panos_ipsec_tunnel:
      anti_replay: false 

it should disable the Replay Protection option for the tunnel. 

## Current behavior

I have set "anti_replay: no" in my task in the ansible playbook, but even though ansible takes the value, the "after" state still configures <anti-replay>**yes**</anti-replay>:

Extract from playbook run:

changed: [my_hostname] => {
    "changed": true,
    "diff": {
        "after": "<?xml version=\"1.0\" encoding=\"utf-8\"?><anti-replay>**yes**</anti-replay>
        "before": "<?xml version=\"1.0\" encoding=\"utf-8\"?><anti-replay>**no**</anti-replay>
    },
    "invocation": {
        "module_args": {
            "ak_ike_gateway": "YYY",
            "ak_ipsec_crypto_profile": "YYY",
            **"anti_replay": false,**
            "api_key": null,
            "commit": false,
            "copy_flow_label": false,
            "copy_tos": false,
            "disabled": false,
            "enable_tunnel_monitor": false,
            "gps_certificate_profile": null,
            "gps_interface": null,
            "gps_interface_ipv4_floating_ip": null,
            "gps_interface_ipv4_ip": null,
            "gps_interface_ipv6_floating_ip": null,
            "gps_interface_ipv6_ip": null,
            "gps_local_certificate": null,
            "gps_portal_address": null,
            "gps_prefer_ipv6": false,
            "gps_publish_connected_routes": false,
            "gps_publish_routes": null,
            "ip_address": null,
            "ipv6": false,
            "mk_auth_key": null,
            "mk_auth_type": null,
            "mk_esp_encryption": null,
            "mk_esp_encryption_key": null,
            "mk_interface": null,
            "mk_local_address_floating_ip": null,
            "mk_local_address_ip": null,
            "mk_local_spi": null,
            "mk_protocol": null,
            "mk_remote_address": null,
            "mk_remote_spi": null,
            "name": "XXX",
            "password": null,
            "port": 443,
            "provider": {
                "api_key": null,
                "ip_address": "XX.XX.XX.XX",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 443,
                "serial_number": null,
                "username": "my_username"
            },
            "state": "present",
            "template": null,
            "template_stack": null,
            "tunnel_interface": "tunnel.2",
            "tunnel_monitor_dest_ip": null,
            "tunnel_monitor_profile": null,
            "tunnel_monitor_proxy_id": null,
            "type": "auto-key",
            "username": "admin"
        }
    }
}

## Possible solution

No idea, but I think that the pandevice framework, might cause the problem. 

## Steps to reproduce

          - name: Enable XXX Tunnel
            panos_ipsec_tunnel:
              provider: "{{ provider }}"
              name: "XXX"
              disabled: no
              anti_replay: no
              ak_ike_gateway: "YYY"
              ak_ipsec_crypto_profile: "YYY"
              type: "auto-key"
              tunnel_interface: "tunnel.2"
              ipv6: no
              copy_flow_label: no
              copy_tos: no
              enable_tunnel_monitor: no
              state: present
              commit: False

## Screenshots

![image](https://user-images.githubusercontent.com/18590395/95096451-f1b81900-0734-11eb-988d-afe8fd722286.png)

## Context

I am trying to enable/disable my ipsec tunnels, but since the pan_ipsec_tunnel module sets default values for some parameters if not defined, I have to define all of those, to make sure the module won't set the default values. One of those is "anti_replay" and for some tunnels I must have it off and currently it just doesn't work. 

## Your Environment

- Version used: PANOS v 8.1.7, 
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python 3.8.5
- Operating System and version (desktop or mobile): Ubuntu 20.04 LTS
- Link to your project:

**Comment by mrichardson03** [comment]
Please read the top of the issue template, and report this against the collection instead.

**Comment by tedolin** [comment]
Thank you Michael, will do. 
Apologies.
