### ISSUE TITLE
[DEPRECATION WARNING]: Classic provider params are deprecated; use "provider" instead.

### ISSUE THREAD

**Issue by rziemlak** [PaloAltoNetworks/ansible-pan#504]
Hi,

I am currently working on network automation with Ansible.
I got everything ready and it worked but ran into an unexpected problem.

When I run my playbook, I've got this warning:

> [DEPRECATION WARNING]: Classic provider params are deprecated; use "provider" instead. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Example playbook (random parameters used):

>  - hosts: pa-vm
>   connection: local
>   gather_facts: True
> 
>   roles:
>     - role: PaloAltoNetworks.paloaltonetworks
> 
>   tasks:
>   - name: Grab the credentials from ansible-vault
>     include_vars: 'firewall-secrets.yml'
>     no_log: 'yes'
>   
>   - name: Create interface tunnel.11
>     panos_tunnel:
>       ip_address: '{{ ip_address }}'
>       username: '{{ username }}'
>       password: '{{ password }}'
>       if_name: "tunnel.11"
>       ip: "1.2.3.{{ uniquenumber }}"
>       zone_name: 'zone1'
>       vr_name: 'vr1'
>       comment: 'comment'
> 
>   - name: Create IKE Gateway
>     panos_ike_gateway:
>       ip_address: '{{ ip_address }}'
>       username: '{{ username }}'
>       password: '{{ password }}'
>       name: 'name'
>       version: 'ikev2'
>       interface: 'ethernet1/2'
>       enable_passive_mode: False
>       enable_liveness_check: True
>       peer_ip_value: '172.16.0.1'
>       pre_shared_key: 'sample_key'
>       ikev2_crypto_profile: 'ike-crypto'
>       local_id_type: 'ufqdn'
>       local_id_value: '{{ uniquename }}@domain.local'
>       enable_nat_traversal: True
> 
>   - name: Create IPSec Tunnel
>     panos_ipsec_tunnel:
>       ip_address: '{{ ip_address }}'
>       username: '{{ username }}'
>       password: '{{ password }}'
>       name: 'name'
>       tunnel_interface: 'tunnel.11'
>       ak_ike_gateway: 'name'
>       state: 'present'
>       ak_ipsec_crypto_profile: 'ipsec-crypto'
>       tunnel_monitor_dest_ip: '1.2.4.{{ uniquenumber }}'
>       tunnel_monitor_profile: 'default-failover'
>       enable_tunnel_monitor: True
> 
>   - name: Commit pending firewall changes
>     panos_commit:
>       ip_address: '{{ ip_address }}'
>       username: '{{ username }}'
>       password: '{{ password }}'
> 

Example inventory:

> [pa-vm]
> pa-vm1 ip_address=172.31.250.1 uniquenumber=1 uniquename=TEST1
> pa-vm2 ip_address=172.31.250.2 uniquenumber=2 uniquename=TEST2
> pa-vm3 ip_address=172.31.250.3 uniquenumber=3 uniquename=TEST3

And example firewall-secrets.yml

> username: 'admin'
> password: 'password'
> 

I know i should use provider, instead of an ip_address, username and password in every task in playbook, but I don't know how to use provider parameter when I want playbook to execute on more than one firewall. I know I can do something like this for ex.:
>  pa-vm1:
>    ip_address: '172.31.250.1
>    username: 'admin'
>    password: 'password'
>  pa-vm2:
>    ip_address: '172.31.250.2
>    username: 'admin'
>    password: 'password'
>  pa-vm3:
>    ip_address: '172.31.250.3
>    username: 'admin'
>    password: 'password'

But how to execute it one more than one device? 
In all example playbooks all I can find is "provider: '{{ provider }}'". No examples of how the structure of a file with providers should look, to use it for more than one device. Can somebody help me? How to execute playbook on more than one device using "provider"?

**Comment by mrichardson03** [comment]
Please note, the Ansible Galaxy role is now deprecated in favor for the new Ansible collection and no new features will be added to it. Please begin using the Ansible collection instead.
