### ISSUE TITLE
panos_op module enhancement - wait_for

### ISSUE THREAD

**Issue by yenlinsu** [PaloAltoNetworks/ansible-pan#57]
would like to have this module enhanced a bit to add a “wait_for” option, so the module doesn’t exit until the condition is satisfied in the wait_for.
Eg. Cmd: run request system software download version 8.0.5, run show jobs id xxx, wait_for: result[1] contains FIN

**Comment by ivanbojer** [comment]
Ansible already has built-in mechanism for this. See this for example:
https://github.com/PaloAltoNetworks/ansible-pan/blob/develop/examples/fw_op_loop.yml

...if you are talking about software upgrades in general look for upcoming panos_software module. The above example is generic for any operation of that type.
