### ISSUE TITLE
panos_mgtconfig - Error when attempting to set NTP primary and secondary server

### ISSUE THREAD

**Issue by smatt241** [PaloAltoNetworks/ansible-pan#65]
The full traceback is:
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.5/site-packages/pandevice/base.py", line 3085, in method
    super_method(self, *args, **kwargs)
  File "/home/matt/.local/lib/python3.5/site-packages/pan/xapi.py", line 749, in edit
    self.__type_config('edit', query, extra_qs)
  File "/home/matt/.local/lib/python3.5/site-packages/pan/xapi.py", line 805, in __type_config
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  system -> ntp-servers -> primary-ntp-server -> ntp-server-address  is a duplicate node
 system -> ntp-servers -> primary-ntp-server is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_58x5rx_j/ansible_module_panos_mgtconfig.py", line 241, in main
    ss.apply()
  File "/home/matt/.local/lib/python3.5/site-packages/pandevice/base.py", line 522, in apply
    device.xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)
  File "/home/matt/.local/lib/python3.5/site-packages/pandevice/base.py", line 3102, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError:  system -> ntp-servers -> primary-ntp-server -> ntp-server-address  is a duplicate node
 system -> ntp-servers -> primary-ntp-server is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_58x5rx_j/ansible_module_panos_mgtconfig.py", line 251, in <module>
    main()
  File "/tmp/ansible_58x5rx_j/ansible_module_panos_mgtconfig.py", line 246, in main
    module.fail_json(msg=exc.message)
AttributeError: 'PanDeviceXapiError' object has no attribute 'message'

failed: [192.168.77.250 -> localhost] (item={'primary': '1.1.1.1', 'secondary': '2.2.2.2'}) => {
    "changed": false,
    "failed": true,
    "item": {
        "primary": "1.1.1.1",
        "secondary": "2.2.2.2"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/matt/.local/lib/python3.5/site-packages/pandevice/base.py\", line 3085, in method\n    super_method(self, *args, **kwargs)\n  File \"/home/matt/.local/lib/python3.5/site-packages/pan/xapi.py\", line 749, in edit\n    self.__type_config('edit', query, extra_qs)\n  File \"/home/matt/.local/lib/python3.5/site-packages/pan/xapi.py\", line 805, in __type_config\n    raise PanXapiError(self.status_detail)\npan.xapi.PanXapiError:  system -> ntp-servers -> primary-ntp-server -> ntp-server-address  is a duplicate node\n system -> ntp-servers -> primary-ntp-server is invalid\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_58x5rx_j/ansible_module_panos_mgtconfig.py\", line 241, in main\n    ss.apply()\n  File \"/home/matt/.local/lib/python3.5/site-packages/pandevice/base.py\", line 522, in apply\n    device.xapi.edit(self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC)\n  File \"/home/matt/.local/lib/python3.5/site-packages/pandevice/base.py\", line 3102, in method\n    raise the_exception\npandevice.errors.PanDeviceXapiError:  system -> ntp-servers -> primary-ntp-server -> ntp-server-address  is a duplicate node\n system -> ntp-servers -> primary-ntp-server is invalid\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_58x5rx_j/ansible_module_panos_mgtconfig.py\", line 251, in <module>\n    main()\n  File \"/tmp/ansible_58x5rx_j/ansible_module_panos_mgtconfig.py\", line 246, in main\n    module.fail_json(msg=exc.message)\nAttributeError: 'PanDeviceXapiError' object has no attribute 'message'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by smatt241** [comment]
#41

**Comment by fvigo** [comment]
Created https://github.com/PaloAltoNetworks/ansible-pan/pull/206 to address it

**Comment by shinmog** [comment]
Fixed by #206
