### ISSUE TITLE
Fail on Delete Specific Object from Object Group

### ISSUE THREAD

**Issue by arkaraung1993** [PaloAltoNetworks/ansible-pan#67]
- name: Add an address object to PA
          panos_object:
            ip_address: '{{ ansible_ssh_host }}'
            username: '{{ ansible_ssh_user }}'
            password: '{{ ansible_ssh_pass }}'
            addressobject: "test1"
            address: "192.168.1.0/24"
            address_type: 'ip-netmask'
            operation: 'add'

        - name: Add an Another address object to PA
          panos_object:
            ip_address: '{{ ansible_ssh_host }}'
            username: '{{ ansible_ssh_user }}'
            password: '{{ ansible_ssh_pass }}'
            addressobject: "**test2**"
            address: "192.168.2.0/24"
            address_type: 'ip-netmask'
            operation: 'add'

        - name: Add an Object to Object group to the PA
          panos_object:
            ip_address: '{{ ansible_ssh_host }}'
            username: '{{ ansible_ssh_user }}'
            password: '{{ ansible_ssh_pass }}'
            addressgroup: "GROUP-Test123"
            static_value: [ test1, test2 ]
            operation: 'add'

        - name: Remove an address object to PA
          panos_object:
            ip_address: '{{ ansible_ssh_host }}'
            username: '{{ ansible_ssh_user }}'
            password: '{{ ansible_ssh_pass }}'
            addressobject: "**test1**"
            address: "192.168.1.0/24"
            address_type: 'ip-netmask'
            operation: 'delete'
----------------------------------------
Error Appear 
TASK [Remove an address object to PA] **********************************************************************************************************************************
failed: [pafw]  =>----
 "msg": "**test1** cannot be deleted because of references from:\nstatic  address-group -> **GROUP-Test123** -> static"

**Comment by shinmog** [comment]
Hi @arkaraung1993 - What you're seeing is the expected result.  If you want to remove the "test1" object from the firewall, then your workflow should be updated to look like this:

1. Add address object `test1`
2. Add address object `test2`
3. Add address group `GROUP-Test123` that uses `test1` and `test2`
4. Update `GROUP-Test123` to use only `test2`
5. Delete the `test1` address object

**Comment by shinmog** [comment]
@arkaraung1993 @Madnessy 

Hi guys, the `panos_object` module is now deprecated in favor of the newly added modules which support idempotency.  The update issues you saw should also be addressed:

* panos_address_object
* panos_address_group
* panos_service_object
* panos_service_group
* panos_tag_object
