### ISSUE TITLE
Panorama Support

### ISSUE THREAD

**Issue by lampwins** [PaloAltoNetworks/ansible-pan#8]
Would be nice to have native panorama support. i.e. adding a rule to a particular device group or performing the different panorama commit types. I will probably implement these two features soon.

**Comment by sgzijl** [comment]
+1

**Comment by sfhotter** [comment]
+1

**Comment by amsinha2** [comment]
Has there been any movement on this?

**Comment by msonstei** [comment]
+1

**Comment by ivanbojer** [comment]
Yes, we plan to add support for Panorama on module per module basis. This effort will start once Ansible 2.3 has been released as we are in the process of refactoring the entire code-base.

**Comment by ivanbojer** [comment]
Note: Added support for Panorama in the panos_security_policy module in the development branch.
