### ISSUE TITLE
panos_op module fails with "UnboundLocalError" when interface has a `/` in its name

### ISSUE THREAD

**Issue by zer0nimbus** [PaloAltoNetworks/ansible-pan#80]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- panos_op.py

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.1
  config file = /path/to/config/ansible.cfg
  configured module search path = [u'/path/to/lib/library']
  ansible python module location = /path/to/virtualenv/python2.7/site-packages/ansible
  executable location = /path/to/virtualenv/bin/ansible
  python version = 2.7.14 (default, Oct  2 2017, 12:37:40) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT
Running Ansible on Mac OS X 10.13.3

##### SUMMARY
Using the panos_op module to query for info on an interface with a `/` in its name results in an "UnboundLocalError"

##### STEPS TO REPRODUCE 

Command I am trying to execute:
`show interface ethernet1/12`

output from ansible-playbook command:

```
ansible-playbook -i inventory/inventory.ini -l pan_host playbooks/pan/show_pan_interfaces.yml --ask-vault-pass -e "interface=ethernet1/12"

PLAY [show pan interfaces] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [show_pan_interfaces : debug] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [my_firewall_host_name] => {
    "interface": "ethernet1/12"
}

TASK [show_pan_interfaces : get interface info] ****************************************************************************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'xml_output' referenced before assignment
fatal: [pd-net-panfw-01.explorys.net]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/zl/7hnwrqyj649cgqxw528fl_mh0000gn/T/ansible_c_TN29/ansible_module_panos_op.py\", line 160, in <module>\n    main()\n  File \"/var/folders/zl/7hnwrqyj649cgqxw528fl_mh0000gn/T/ansible_c_TN29/ansible_module_panos_op.py\", line 153, in main\n    obj_dict = xmltodict.parse(xml_output)\nUnboundLocalError: local variable 'xml_output' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

From that error, it's pretty obvious that the issue is that the variable `xml_output` is not being assigned a value. So I debugged the module code manually and found where the problem is:

lines 133 to 140 of panos_op.py:
```  
    try:
        xml_output = device.op(cmd, xml=True)
        changed = True
    except PanXapiError:
        exc = get_exception()

        if 'non NULL value' in exc.message:
            # rewrap and call again
```

if the first `device.op` call fails, it checks the exception message for the string 'non NULL value'. If the response then does not contain that string, `xml_output` is never assigned a value, resulting in an "UnboundLocalError" failure. 

When executing this module with the cmd `show interface ethernet1/12`, the response returned by `xml_output = device.op(cmd, xml=True)` is a `400 reason: bad request`, and as such, it never assigns a value to `xml_output`. If I allow the module to continue past that exception by modifying the conditional to read:
 `if 'non NULL value' or '400 reason: bad request' in exc.message:`,
it executes successfully. And if I manually execute the code in cmd_array/cmd2 creation, it executes successfully as well. 

Here is the debugging I've done so far, running through `panos_op.py`:

```
>>> import pan.xapi
>>> from pan.xapi import PanXapiError
>>> import pandevice
>>> from pandevice import base
>>> from pandevice import firewall
>>> from pandevice import panorama
>>> import xmltodict
>>> import json
>>> ip_address = "[redacted]"
>>> username = "[redacted]"
>>> password = "[redacted]"
>>> cmd = "show interface ethernet1/12"
>>> device = base.PanDevice.create_from_device(ip_address, username, password)
>>> xml_output = device.op(cmd, xml=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/virtualenv/lib/python2.7/site-packages/pandevice/firewall.py", line 180, in op
    return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)
  File "/path/to/virtualenv/lib/python2.7/site-packages/pandevice/base.py", line 3296, in op
    element = self.xapi.op(cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer)
  File "/path/to/virtualenv/lib/python2.7/site-packages/pandevice/base.py", line 3173, in method
    raise the_exception
pandevice.errors.PanURLError: URLError: code: 400 reason: Bad Request
```

#### execute cmd2 creation and execution when cmd = "show interface ethernet1/12"

```
>>> cmd_array = cmd.split()
>>> cmd_array_len = len(cmd_array)
>>> cmd_array[cmd_array_len - 1] = '\"' + cmd_array[cmd_array_len - 1] + '\"'
>>> cmd2 = ' '.join(cmd_array)
>>> xml_output = device.op(cmd2, xml=True)
>>> obj_dict = xmltodict.parse(xml_output)
>>> json_output = json.dumps(obj_dict)
>>> print(json_output)
{"response": {"@status": "success", "result": ...
```

This is where I start to get lost. Presumably, the format of `cmd` being passed to `return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)` in `firewall.py` is being parsed in such a way that the remote device is interpreting it as a bad request, but I'm not entirely sure how to continue debugging this issue. And I do not think it prudent to allow the module to continue execution if the response from the remote device is a "400 reason: bad request". 

Any help would be appreciated.

**Comment by arkaraung1993** [comment]
Hi zer0nimbus,

I am also facing this issue in "panos_op" module.

using command is "test security-policy-match source 10.0.0.111 destination 2.2.2.2 destination-port 443 protocol 6"

Error message:

UnboundLocalError: local variable 'xml_output' referenced before assignment

fatal: [10.88.10.104]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NwWQek/ansible_module_panos_op.py\", line 159, in <module>\n    main()\n  File \"/tmp/ansible_NwWQek/ansible_module_panos_op.py\", line 152, in main\n    obj_dict = xmltodict.parse(xml_output)\nUnboundLocalError: local variable 'xml_output' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

---------------
I try to understand your explanation change in code, but i am not understand what you change in code.

Really appreciate if you help on this issue.

**Comment by zer0nimbus** [comment]
arkaraung1993 - 

I have not yet been able to fix this issue. Sorry if I did not make that clear in my initial post.

**Comment by amsinha2** [comment]
Is there a fix for this yet?

**Comment by shinmog** [comment]
@zer0nimbus 
As it turns out, depending on the command you're attempting to run, you could get one of a few different errors from PAN-OS.  It seems like it's best to just always try to run the command a second time, because in your case of trying to run `show interface ethernet1/12`, running it the second way would actually work.  So I'm going to update the code to do that.

@arkaraung1993 
This module will not in its current form work for that particular command.  The `op` command expects XML as its input, and in this case, the current code would try the following:

`<test><security-policy-match><source><10.0.0.111><destination><2.2.2.2><destination-port><443><protocol><6></6></protocol></443></destination-port></2.2.2.2></destination></10.0.0.111></source></security-policy-match></test>`

...and when that doesn't work, it will try this:

`<test><security-policy-match><source><10.0.0.111><destination><2.2.2.2><destination-port><443><protocol>6</protocol></443></destination-port></2.2.2.2></destination></10.0.0.111></source></security-policy-match></test>`

..But what it actually needs to execute is this:

`<test><security-policy-match><source>10.0.0.111</source><destination>2.2.2.2</destination><destination-port>443</destination-port><protocol>6</protocol></security-policy-match></test>`

I'll open a PR which should solve all of these issues.
