### ISSUE TITLE
panos_match_rule Issue ("ElementTree.fromstring ParseError: not well-formed (invalid token): line 44, column 20)

### ISSUE THREAD

**Issue by arkaraung1993** [PaloAltoNetworks/ansible-pan#89]
COMPONENT NAME
panos_match_rule.py

ANSIBLE VERSION
2.5.2

OS / ENVIRONMENT
Running Ansible on Linux Enterprise 7.4

SUMMARY
Using the panos_match_rule.py module to query for info rule, esults in an "ElementTree.fromstring ParseError: not well-formed (invalid token): line 44, column 20"

STEPS TO REPRODUCE

output from ansible-playbook command:
[root@SGQAAANSV101 test-fw-rule]# ansible-playbook pa_pre_check.yml  -vvvvvv
ansible-playbook 2.5.2
  config file = /var/lib/awx/projects/test-fw-rule/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', 

TASK [PA_Pre_Check Matching Firewall Rule for IP(s) is already exist or not for Host Address] ********************************
task path: /var/lib/awx/projects/test-fw-rule/pa_pre_check.yml:41
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/panos/panos_match_rule.py
<10.89.26.209> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.89.26.209> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.89.26.209> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773 `" && echo ansible-tmp-1525679558.37-60989092725773="` echo /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773 `" ) && sleep 0'
<10.89.26.209> PUT /root/.ansible/tmp/ansible-local-9029I9g0is/tmpqURsqm TO /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773/panos_match_rule.py
<10.89.26.209> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773/ /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773/panos_match_rule.py && sleep 0'
<10.89.26.209> EXEC /bin/sh -c 'PYTHONHTTPSVERIFY=0 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773/panos_match_rule.py && sleep 0'
<10.89.26.209> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1525679558.37-60989092725773/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_PdNWbv/ansible_module_panos_match_rule.py", line 346, in main
    response = device.op(cmd=test_string, vsys=vsys_id)
  File "/usr/lib/python2.7/site-packages/pandevice/firewall.py", line 175, in op
    return super(Firewall, self).op(cmd, vsys, xml, cmd_xml, extra_qs, retry_on_peer)
  File "/usr/lib/python2.7/site-packages/pandevice/base.py", line 3223, in op
    element = self.xapi.op(cmd, vsys, cmd_xml, extra_qs, retry_on_peer=retry_on_peer)
  File "/usr/lib/python2.7/site-packages/pandevice/base.py", line 3102, in method
    raise the_exception

fatal: [10.89.26.209]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "application": null,
            "category": null,
            "destination_ip": "1.1.1.1",
            "destination_port": "21",
            "destination_zone": null,
            "ip_address": "10.89.26.209",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "6",
            "rule_type": "security",
            "source_ip": "10.0.0.111",
            "source_port": null,
            "source_user": null,
            "source_zone": null,
            "to_interface": null,
            "username": "svc_wog_gnlops",
            "vsys_id": "vsys1"
        }
    },
    "msg": "ElementTree.fromstring ParseError: not well-formed (invalid token): line 44, column 20"

Any help would be appreciated.

**Comment by shinmog** [comment]
@arkaraung1993 

It seems like PAN-OS is responding with invalid XML...?

Looking at the args you sent the module, can you do the following on your firewall's CLI and paste the resulting XML:

```bash
$ debug cli on
$ test security-policy-match source 10.0.0.111 destination 1.1.1.1 protocol 6 destination-port 21
```

**Comment by shinmog** [comment]
Assuming this is resolved, closing.
